class Languages {
  static Map<String, Map<String, String>> translations = {
    'ar': {
      'Welcome Laith Haitham Azzam': 'مرحبا',
      'Have A Nice Day At Work': 'أتمنى لك يوم جيد في العمل',
      'Illness and Vaccines': 'الأمراض و اللقحات',
      'Illness': 'الأمراض',
      'Vaccines': 'اللقحات',
      'Rewards and Penalties': 'المكافئات و العقوبات',
      'Rewards': 'المكافئات',
      'Penalties': 'العقوبات',
      'Attendance Today': 'حضور اليوم',
      'Employees\nAttendance': 'حضور الموظفين',
      'Students\nAttendance': 'حضور الطلاب',
      'Teachers\nAttendance': 'حضور المعلمين',
      'Percentage\nStudents': 'نسبة الطلاب',
      'Percentage\nTeacher': 'نسبة المعلمين',
      'Percentage\nEmployee': 'نسبة الموظفين',
      'Total Students': 'إجمالي الطلاب',
      'Total Teacher': 'إجمالي المعلمين',
      'Total Employee': 'إجمالي الموظفين',
      'Total Visitor': 'إجمالي الزائرين',
      'Total Books': 'إجمالي الكتب',
      'Total Division': 'إجمالي الشُعب',
      'Dashboard': 'الإحصائيات',
      'Enroll Requests': 'طلبات التسجيل',
      'Exam Table': "جدول الامتحان",
      'School Time Table': 'جدول الدوام',
      'All Students': 'كل الطلاب',
      'Study Year Students': 'طلاب العام الدراسي',
      'All Guardians': 'أولياء الأمور',
      'Student Attendance': 'حضور الطلاب',
      'Students Attendance Managment': 'إدارة حضور الطلاب',
      'Teacher Management': 'إدارة المعلمين',
      'Teacher Status': 'حضور المعلمين',
      'Teacher Attendance Managment': 'إدارة حضور المعلمين',
      'Employee Management': 'إدارة الموظفين',
      'Employee Attendance': 'حضور الموظفين',
      'Employee Attendance Manage': 'إدارة حضور الموظفين',
      'Virtual User Management': 'إدارة الموظفين الافتراضيين',
      'Session Management': 'إدارة السنوات',
      'Grade Management': 'إدارة المراحل الدراسية',
      'Subject Management': 'إدارة المواد',
      'Class Management': 'إدارة الصفوف',
      'Division Management': 'إدارة الشعب',
      'Curriculum Management': 'إدارة المناهج',
      'School Data Management': 'إدارة معلومات المدرسة',
      'Electronic Library': 'المكتبة الإلكترونية',
      'Transaction': 'سجل المناقلات',
      'Illness Screen': 'الأمراض',
      'Vaccine Screen': 'اللقاحات',
      'Presence of students': 'نسب الطلاب',
      'Presence this session students': 'نسب طلاب هذا العام',
      'Total this year': 'إجمالي هذه السنة',
      'Add': 'إضافة',
      'Penalty En - Name': 'الاسم الإنكليزي للعقوبة',
      'Penalty Ar - Name': 'الاسم العربي للعقوبة',
      'Details': 'تفاصيل',
      'Add Penalty': 'إضافة عقوبة',
      'Delete': 'حذف',
      'Cancel': 'إلغاء',
      'Do You Want To Delete': 'هل تريد حذف العقوبة',
      'penalty': '',
      'Edit': 'تعديل',
      'Operation': 'العمليات',
      'Penalty Name': 'اسم العقوبة',
      'Delete Penalty': 'حذف العقوبة',
      'Edit Penalty': 'تعديل العقوبة',
      'Status': 'الحالة',
      'No Requests': 'لا يوجد طلبات',
      'Guardian Info :': 'معلومات ولي الأمر:',
      'Name :': 'الاسم:',
      'Mobile:': 'الهاتف:',
      'Email: ': 'البريد الإلكتروني: ',
      'National ID:': 'الرقم الوطني:',
      'Student Info:': 'معلومات الطالب:',
      'Current Class:': 'الصف الحالي:',
      'Previous Class:': 'الصف السابق',
      'Manage': 'إدارة',
      'Reject': 'رفض',
      'Approve': 'موافقة',
      'Rejected': 'مرفوض',
      'Pending': 'معلق',
      'Partially': 'جزئياً',
      'Search By Name': 'البحث حسب الاسم',
      'Class': 'الصف',
      'Division': 'شعبة',
      'Manage Student': 'إدارة الطالب',
      'Add Exam': 'إضافة امتحان',
      'Date': 'التاريح',
      'Type': 'النوع',
      'Curriculum Name': 'اسم المنهاج',
      'Period': 'الفترة الزمنية',
      'Max Mark': 'العلامة العظمى',
      'Passing Mark': 'الحد الأدنى للنجاح',
      'Operations': 'العمليات',
      'Edit Exam': 'تعديل الامتحان',
      'Semester': 'الفصل',
      'Curriculum': 'المنهاج',
      'season': 'الفصل',
      'New Text': 'نص جديد',
      'Min Mark': 'الحد الأدنى للنجاح',
      'Time': 'الوقت',
      'Morning': 'صباحي',
      'Evening': 'مسائي',
      'WE CARE ABOUT \n YOUR FUTURE': 'نحن نعتني\n بمستقبلك',
      'Join us to enter a better world filled with advanced educational methods through Virtual Modern School':
          'انضم إلينا لدخول عالم أفضل مليء بالأساليب التعليمية المتطورة من خلال المدرسة الافتراضية الحديثة',
      'Enroll': 'تسجيل',
      'Sign In': 'تسجيل دخول',
      'Teachers': 'المعلمين',
      'Students': 'الطلاب',
      'Visitors': 'الزائرين',
      'Search': 'البحث',
      'Settings': 'الاعدادات',
      'Profile': 'صفحتي',
      'Personal': 'شخصي',
      'Password': 'كلمة السر',
      'Account And Password': 'الحساب و كلمة السر',
      'Appearance': 'المظهر و اللغة',
      'Light Theme': 'النمط الفاتح',
      'Dark Theme': 'النمط الداكن',
      'Language': 'اللغة',
      'English': 'English',
      'Arabic': 'العربية',
      'My Email': 'بريدي الالكتروني',
      'Edit Picture': 'تعديل الصورة',
      'Delete Picture': 'حذف الصورة',
      'Logout': 'تسجيل الخروج',
      'Bank Info': 'معلومات الحساب و الدفع',
      'Personal Information': 'معلوماتي العامة',
      'Application and Profile Settings': 'اعدادات التطبيق و الملف الشخصي',
      'Application Theem': 'نمط التطبيق',
      'Social Media Info': 'معلومات التواصل الاجتماعي',
      'Your Password': 'كلمتي السرية',
      'Old Password': 'كلمة السر القديمة',
      'Your Verification Code': 'رمز التحقق',
      'Change Password': 'تغيير كلمة السر',
      'New Password': 'كلمة السر الجديدة',
      'Confirm New Password': 'تأكيد كلمة السر الجديدة',
      'More Information': 'معلومات اضافية',
      'Technical Support': 'دعم تقني',
      'First Name': 'الاسم الأول',
      'Last Name': 'الاسم الأخير',
      'Phone Number': 'رقم الهاتف',
      'Emergency Number': 'رقم هاتف للطوارئ',
      'Join Date': 'تاريخ الانضمام',
      'Birthdate': 'تاريخ الميلاد',
      'Address': 'العنوان',
      'Current Address': 'العنوان الحالي',
      'Gender': 'الجنس',
      'Family Status': 'الحالة الأُسرية',
      'Career History': 'المسيرة المهنية',
      'Qualification': 'المؤهلات',
      'Experience': 'الخبرات',
      'Note': 'ملاحظات',
      'Facebook URL': 'رابط حسابك الفيسبوك ',
      'Instagram URL': 'رابط حسابك الانستغرام ',
      'X Platform URL': 'X رابط حسابك منصة',
      'Linkedin URL': 'رابط حسابك اللينكد إن ',
      'Bank Name': 'اسم البنك',
      'Bank Account Title': 'اسم الحساب البنكي',
      'Bank Branch Name': 'اسم الفرع البنكي',
      'Bank Account Number': 'رقم الحساب البنكي',
      'Save': 'حفظ',
      '': '',
      'Select Class First': 'اختر الصف أولاً',
      'Select Division First': 'اختر الشعبة أولاً',
      'Day': 'اليوم',
      'Teacher': 'المعلم',
      'Operation of Lessons': 'العلميات على الحصص الدراسية',
      'Sunday': 'الأحد',
      'Monday': 'الإثنين',
      'Tuesday': 'الثلاثاء',
      'Wednesday': 'الأربعاء',
      'Thursday': 'الخميس',
      'First\n Lesson': 'الحصة \n الأولى',
      'second\n Lesson': 'الحصة \n الثانية',
      'Third\n Lesson': 'الحصة \n الثالثة',
      'Forth\n Lesson': 'الحصة \n الرابعة',
      'Fifth\n Lesson': 'الحصة \n الخامسة',
      'Sixth\n Lesson': 'الحصة \n السادسة',
      'Seventh\n Lesson': 'الحصة \n السابعة',
      'Session': 'العام الدراسي',
      'Grade': 'المرحلة الدراسية',
      'Email:': 'البريد الألكتروني::',
      'Grade Level:': 'المرحلة الدراسية:',
      'Delete Students': 'حذف الطالب',
      'Student': '',
      'No Students': 'لا يوجد طلاب',
      'Reward': 'المكافآت',
      'Penalty': 'العقوبات',
      'Start Date': 'تاريخ البداية',
      'End Date': 'تاريخ النهاية',
      'Reason': 'السبب',
      'Penalties And Rewards': 'المكافآت و العقوبات',
      'Passing': 'ناجح',
      'Failed': 'راسب',
      'Export Certificate': 'تصدير الجلاء',
      'Send': 'إرسال',
      'Logout from Current Session': 'تسجيل الخروج من الجلسة الحالية',
      'Logout from All Sessions': 'تسجيل الخروج من كافة الجلسات',
      'Penaltyy': 'عقوبة',
      'The Reason': 'السبب',
      'Punishing Student': 'معاقبة الطالب',
      'Punishing': 'معاقبة',
      'Contact Us': 'التواصل معنا',
      'AboutUs': 'حول',
      'WhyUs': 'لماذا نحن',
      'Programs': 'البرمامج',
      'Enrollment': 'التسجيل',
      'Eligibility': 'المؤهلون',
      'Who Can We Register At Virtual Modern School':
          'من يمكنهم التسجيل في المدرسة الافتراضية الحديثة',
      'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary':
          'من يمكنهم التسجيل في المدرسة الافتراضية الحديثة كل من يقيم خارج سوريا يمكنه التسجيل والتخرج ',
      'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted':
          'ويرغب في تعلم المناهج التربوية السورية من المرحلة الابتدائية إلى المتوسطة والثانوية',
      'by the Ministry of Education at Syrian Arab Republic':
          'يمكنه التسجيل والتخرج للحصول على شهادة الثانوية العامة ',
      'Back': 'رجوع',
      'Add Students': 'إضافة طالب',
      'Mobile Number :': 'رقم الهاتف:',
      'Select Garduans To Add Students': 'اختر ولي الأمر لإضافة طلاب',
      'First Name': 'الاسم الأول',
      'Last Name': 'اسم الأخير',
      'Place Of Birth': 'مكان الولادة',
      'Birthdate': 'تاريخ الولادة',
      'Gender': 'الجنس',
      'Religion': 'الدين',
      'Blood Type': 'زمرة الدم',
      'Location': 'الموقع',
      'Mobile Number': 'رقم الهاتف',
      'FamilyState': 'الحالة الأسرية',
      'National Id': 'الرقم الوطني',
      'Current Address': 'العنوان الحالي',
      'Special need': 'ذوي احتياجات خاصة',
      'Martyr son': 'ابن شهيد',
      'Student Illness': 'أمراض الطالب',
      'Student Vaccines': 'لقاحات الطالب',
      '   Student School Info   ': '   معلومات الطالب المدرسية   ',
      'Username': 'اسم المستخدم',
      'Fee Discount': 'نسبة الخصم',
      '   Father Info   ': '   معلومات الأب   ',
      'Father Name': 'اسم الأب',
      'Father Phone': 'رقم هاتف الأب',
      'Father Work': 'عمل الأب',
      '   Mother Info   ': '   معلومات الأم   ',
      'Mother Name': 'اسم الأم',
      'Mother Phone': 'رقم هاتف الأم',
      'Mother Work': 'عما الأم',
      '   More Info   ': '   معلومات أخرى   ',
      'Last School Details': 'تفاصيل المدرسة السابقة',
      'Note': 'ملاحظات ',
      '   File Data   ': '   بيانات الملفات   ',
      'Add Father Passport': 'إضافة جواز سفر الأب',
      'File Father Passport Dropped!': 'جواز سفر الأب تم لصقه',
      'Add Mother Passport': 'إضافة جواز سفر الأم',
      'File Mother Passport Dropped!': 'جواز سفر الأم تم لصقه',
      'Add Son Passport': 'إضافة جواز سفر الابن',
      'File Son Passport Dropped!': 'جواز سفر الابن تم لصقه',
      'Add ID File': 'إضافة ملف التعريف الشخصي',
      'File Id Dropped!': 'ملف التعريف تم لصقه',
      'Add Certificate': 'إضافة شهادة',
      'File Certificate Dropped!': 'الشهادة تم لصقها',
      'Add Academic sequence': 'إضافة تسلسل أكاديمي',
      'File Academic sequence Dropped!': 'التسلسل الأكديمي تم لصقه',
      'Add Family notebook': 'إضافة دفتر العائلة',
      'File Family notebook Dropped!': 'دفتر العائلة تم لصقه',
      "Local ID": "رقم التعريف الشخصي المحلي",
      'Male': 'ذكر',
      'Female': 'أنثى',
      'Muslim': 'مسلم',
      'Christian': 'مسيحي',
      'Widow': 'أرمل',
      'Single': 'أعزب',
      'Syria': 'سوريا',
      'Married': 'متزوج',
      'Divorced': 'مطلق',
      'Click To Add Father Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الأب\nأو\nاسحب وأفلت الملف هنا',
      'Done Selected File': 'تم اختيار الملف',
      'Click To Add Mother Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الأم\nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Son Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الابن\nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Id\nOr\nDrag And Drop File Here':
          'اضغط لإضافة ملف التعريف الشخصي  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Certificate\nOr\nDrag And Drop File Here':
          'اضغط لإضافة شهادة  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Academic sequence\nOr\nDrag And Drop File Here':
          'اضغط لإضافة تسلسل أكديمي  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Family notebook\nOr\nDrag And Drop File Here':
          'اضغط لإضافة دفتر العائلة  \nأو\nاسحب وأفلت الملف هنا',
      'Student illeness': 'أمراض الطالب',
      'Done': "تم",
      'Student Vaccine': "لقاحات الطالب"
    },
    'en': {
      'Welcome Laith Haitham Azzam': 'Welcome Laith Haitham Azzam',
      'Have A Nice Day At Work': 'Have A Nice Day At Work',
      'Illness and Vaccines': 'Illness and Vaccines',
      'Illness': 'Illness',
      'Vaccines': 'Vaccines',
      'Rewards and Penalties': 'Rewards and Penalties',
      'Rewards': 'Rewards',
      'Penalties': 'Penalties',
      'Attendance Today': 'Attendance Today',
      'Employees\nAttendance': 'Employees\nAttendance',
      'Students\nAttendance': 'Students\nAttendance',
      'Teachers\nAttendance': 'Teachers\nAttendance',
      'Percentage\nStudents': 'Percentage\nStudents',
      'Percentage\nTeacher': 'Percentage\nTeacher',
      'Percentage\nEmployee': 'Percentage\nEmployee',
      'Total Students': 'Total Students',
      'Total Teacher': 'Total Teacher',
      'Total Employee': 'Total Employee',
      'Total Visitor': 'Total Visitor',
      'Total Books': 'Total Books',
      'Total Division': 'Total Division',
      'Dashboard': 'Dashboard',
      'Enroll Requests': 'Enroll Requests',
      'Exam Table': "Exam Table",
      'School Time Table': 'School Time Table',
      'All Students': 'All Students',
      'Study Year Students': 'Study Year Students',
      'All Guardians': 'All Guardians',
      'Student Attendance': 'Student Attendance',
      'Students Attendance Managment': 'Students Attendance Managment',
      'Teacher Management': 'Teacher Management',
      'Teacher Status': 'Teacher Status',
      'Teacher Attendance Managment': 'Teacher Attendance Managment',
      'Employee Management': 'Employee Management',
      'Employee Attendance': 'Employee Attendance',
      'Employee Attendance Manage': 'Employee Attendance Manage',
      'Virtual User Management': 'Virtual User Management',
      'Session Management': 'Session Management',
      'Grade Management': 'Grade Management',
      'Subject Management': 'Subject Management',
      'Class Management': 'Class Management',
      'Division Management': 'Division Management',
      'Curriculum Management': 'Curriculum Management',
      'School Data Management': 'School Data Management',
      'Electronic Library': 'Electronic Library',
      'Transaction': 'Transaction',
      'My Email': 'My Email',
      'Illness Screen': 'Illness Screen',
      'Vaccine Screen': 'Vaccine Screen',
      'Presence of students': 'Presence of students',
      'Presence this session students': 'Presence 2024 students',
      'Total this year': 'Total this year',
      'Add': 'Add',
      'Penalty En - Name': 'Penalty En - Name',
      'Penalty Ar - Name': 'Penalty Ar - Name',
      'Details': 'Details',
      'Add Penalty': 'Add Penalty',
      'Delete': 'Delete',
      'Cancel': 'Cancel',
      'Old Password': 'Old Password',
      'Do You Want To Delete': 'Do You Want To Delete',
      'penalty': 'penalty',
      'Edit': 'Edit',
      'Operation': 'Operation',
      'Penalty Name': 'Penalty Name',
      'Delete Penalty': 'Delete Penalty',
      'Edit Penalty': 'Edit Penalty',
      'Status': 'Status',
      'No Requests': 'No Requests',
      'Guardian Info :': 'Guardian Info :',
      'Name :': 'Name :',
      'Mobile:': 'Mobile:',
      'Email: ': 'Email: ',
      'National ID:': 'National ID:',
      'Student Info:': 'Student Info:',
      'Current Class:': 'Current Class:',
      'Previous Class:': 'Previous Class',
      'Manage': 'Manage',
      'Reject': 'Reject',
      'Approve': 'Approve',
      'Rejected': 'Rejected',
      'Pending': 'Pending',
      'Partially': 'Partially',
      'Search By Name': 'Search By Name',
      'Class': 'Class',
      'Division': 'Division',
      'Manage Student': 'Manage Student',
      'Add Exam': 'Add Exam',
      'Date': 'Date',
      'Type': 'Type',
      'Curriculum Name': 'Curriculum Name',
      'Period': 'Period',
      'Max Mark': 'Max Mark',
      'Passing Mark': 'Passing Mark',
      'Operations': 'Operations',
      'Edit Exam': 'Edit Exam',
      'Semester': 'Semester',
      'Curriculum': 'Curriculum',
      'season': 'semester',
      'New Text': 'New Text',
      'Min Mark': 'Min Mark',
      'Time': 'Time',
      'Morning': 'Morning',
      'Evening': 'Evening',
      'WE CARE ABOUT \n YOUR FUTURE': 'WE CARE ABOUT \n YOUR FUTURE',
      'Join us to enter a better world filled with advanced educational methods through Virtual Modern School':
          'Join us to enter a better world filled with advanced educational methods through Virtual Modern School',
      'Enroll': 'Enroll',
      'Sign In': 'Sign In',
      'Teachers': 'Teachers',
      'Students': 'Students',
      'Visitors': 'Visitors',
      'Search': 'Search',
      'Settings': 'Settings',
      'Profile': 'Profile',
      'Personal': 'Personal',
      'Password': 'Password',
      'Appearance': 'Appearance and Language',
      'Light Theme': 'Light Theme',
      'Dark Theme': 'Dark Theme',
      'Language': 'Language',
      'English': 'English',
      'Arabic': 'العربية',
      'Logout': 'Logout',
      'Logout from Current Session': 'Logout from Current Session',
      'Logout from All Sessions': 'Logout from All Sessions',
      'Edit Picture': 'Edit Picture',
      'Delete Picture': 'Delete Picture',
      'Application Theem': 'Application Theme',
      'Application and Profile Settings': 'Application and Profile Settings',
      '': '',
      'Personal Information': 'My General Details',
      'Social Media Info': 'Social Media Info',
      'Bank Info': 'Bank Info',
      'Account And Password': 'Account And Password',
      'Your Password': 'Your Password',
      'Your Verification Code': 'Your Verification Code',
      'Change Password': 'Change Password',
      'New Password': 'New Password',
      'Confirm New Password': 'Confirm New Password',
      'More Information': 'More Information',
      'First Name': 'First Name',
      'Last Name': 'Last Name',
      'Phone Number': 'Phone Number',
      'Emergency Number': 'Emergency Number',
      'Join Date': 'Join Date',
      'Birthdate': 'Birthdate',
      'Address': 'Address',
      'Current Address': 'Current Address',
      'Gender': 'Gender',
      'Family Status': 'Family Status',
      'Career History': 'Career History',
      'Qualification': 'Qualification',
      'Experience': 'Experience',
      'Note': 'Note',
      'Save': 'Save',
      'Facebook URL': 'Facebook URL',
      'Instagram URL': 'Instagram URL',
      'X Platform URL': 'X Platform URL',
      'Linkedin URL': 'Linkedin URL',
      'Bank Name': 'Bank Name',
      'Bank Account Title': 'Bank Account Title',
      'Bank Branch Name': 'Bank Branch Name',
      'Bank Account Number': 'Bank Account Number',
      'Select Class First': 'Select Class First',
      'Select Division First': 'Select Division First',
      'Day': 'Day',
      'Teacher': 'Teacher',
      'Operation of Lessons': 'Operation of Lessons',
      'Sunday': 'Sunday',
      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'First\n Lesson': 'First\n Lesson',
      'second\n Lesson': 'second\n Lesson',
      'Third\n Lesson': 'Third\n Lesson',
      'Forth\n Lesson': 'Forth\n Lesson',
      'Fifth\n Lesson': 'Fifth\n Lesson',
      'Sixth\n Lesson': 'Sixth\n Lesson',
      'Seventh\n Lesson': 'Seventh\n Lesson',
      'Session': 'Session',
      'Grade': 'Grade',
      'Email:': 'Email:',
      'Grade Level:': 'Grade Level:',
      'Delete Students': 'Delete Students',
      'Student': 'Student',
      'No Students': 'No Students',
      'Reward': 'Reward',
      'Penalty': 'Penalty',
      'Start Date': 'Start Date',
      'End Date': 'End Date',
      'Reason': 'Reason',
      'Penalties And Rewards': 'Penalties And Rewards',
      'Passing': 'Passing',
      'Failed': 'Failed',
      'Export Certificate': 'Export Certificate',
      'Send': 'Send',
      'Penaltyy': 'Penalty',
      'The Reason': 'The Reason',
      'Punishing Student': 'Punishing Student',
      'Punishing': 'Punishing',
      'Contact Us': 'Contact Us',
      'AboutUs': 'AboutUs',
      'WhyUs': 'WhyUs',
      'Programs': 'Programs',
      'Enrollment': 'Enrollment',
      'Eligibility': 'Eligibility',
      'Who Can We Register At Virtual Modern School':
          'Who Can We Register At Virtual Modern School',
      'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary':
          'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary',
      'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted':
          'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted',
      'by the Ministry of Education at Syrian Arab Republic':
          'by the Ministry of Education at Syrian Arab Republic',
      'Back': 'Back',
      'Add Students': 'Add Students',
      'Mobile Number :': 'Mobile Number :',
      'Select Garduans To Add Students': 'Select Garduans To Add Students',
      'Place Of Birth': 'Place Of Birth',
      'Religion': 'Religion',
      'Blood Type': 'Blood Type',
      'Location': 'Location',
      'Mobile Number': 'Mobile Number',
      'FamilyState': 'FamilyState',
      'National Id': 'National Id',
      'Special need': 'Special need',
      'Martyr son': 'Martyr son',
      'Student Illness': 'Student Illness',
      'Student Vaccines': 'Student Vaccines',
      '   Student School Info   ': '   Student School Info   ',
      'Username': 'Username',
      'Fee Discount': 'Fee Discount',
      '   Father Info   ': '   Father Info   ',
      'Father Name': 'Father Name',
      'Father Phone': 'Father Phone',
      'Father Work': 'Father Work',
      '   Mother Info   ': '   Mother Info   ',
      'Mother Name': 'Mother Name',
      'Mother Phone': 'Mother Phone',
      'Mother Work': 'Mother Work',
      '   More Info   ': '   More Info   ',
      'Last School Details': 'Last School Details',
      '   File Data   ': '   File Data   ',
      'Add Father Passport': 'Add Father Passport',
      'File Father Passport Dropped!': 'File Father Passport Dropped!',
      'Add Mother Passport': 'Add Mother Passport',
      'File Mother Passport Dropped!': 'File Mother Passport Dropped!',
      'Add Son Passport': 'Add Son Passport',
      'File Son Passport Dropped!': 'File Son Passport Dropped!',
      'Add ID File': 'Add ID File',
      'File Id Dropped!': 'File Id Dropped!',
      'Add Certificate': 'Add Certificate',
      'File Certificate Dropped!': 'File Certificate Dropped!',
      'Add Academic sequence': 'Add Academic sequence',
      'File Academic sequence Dropped!': 'File Academic sequence Dropped!',
      'Add Family notebook': 'Add Family notebook',
      'File Family notebook Dropped!': 'File Family notebook Dropped!',
      'Local ID': 'Local ID',
      'Male': 'Male',
      'Female': 'Female',
      'Muslim': 'Muslim',
      'Christian': 'Christian',
      'Widow': 'Widow',
      'Single': 'Single',
      'Married': 'Married',
      'Divorced': 'Divorced',
      'Click To Add Father Passport\nOr\nDrag And Drop File Here':
          'Click To Add Father Passport\nOr\nDrag And Drop File Here',
      'Done Selected File': 'Done Selected File',
      'Click To Add Mother Passport\nOr\nDrag And Drop File Here':
          'Click To Add Mother Passport\nOr\nDrag And Drop File Here',
      'Click To Add Son Passport\nOr\nDrag And Drop File Here':
          'Click To Add Son Passport\nOr\nDrag And Drop File Here',
      'Click To Add Id\nOr\nDrag And Drop File Here':
          'Click To Add Id\nOr\nDrag And Drop File Here',
      'Click To Add Certificate\nOr\nDrag And Drop File Here':
          'Click To Add Certificate\nOr\nDrag And Drop File Here',
      'Click To Add Academic sequence\nOr\nDrag And Drop File Here':
          'Click To Add Academic sequence\nOr\nDrag And Drop File Here',
      'Click To Add Family notebook\nOr\nDrag And Drop File Here':
          'Click To Add Family notebook\nOr\nDrag And Drop File Here',
      'Syria': 'Syria',
      'Done': 'Done',
      'Student illeness': 'Student illeness',
      'Student Vaccine': 'Student Vaccine',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
    }
  };
}
