class Languages {
  static Map<String, Map<String, String>> translations = {
    'ar': {
      'Welcome Laith Haitham Azzam': 'مرحبا',
      'Have A Nice Day At Work': 'أتمنى لك يوم جيد في العمل',
      'Illness and Vaccines': 'الأمراض و اللقحات',
      'Illness': 'الأمراض',
      'Files': 'الملفات',
      'Links': 'الروابط',
      'My Children': 'ابنائي',
      'Forgot your password  ?': 'هل نسيت كلمة السر  ؟',
      'Pages': 'الصفحات',
      'Quiz': 'الاختبارات',
      'You Don`t Have Account ?': 'لا تملك حساب ؟',
      'Question Bank': 'بنك الاسئلة',
      'Trivia': 'السبور',
      'Resend!': 'اعادة ارسال!',
      'Verify': 'التحقق',
      'There is no open academic year available to add classes to. Please add an open academic year and try again.':
          'لا توجد سنة دراسية مفتوحة بعد لاضافة صفوف اليها الرجاء اضافة سنة دراسية مفتوحة و قم بالمحاولة مجدداً',
      'No Penalties': 'لا يوجد عقوبات',
      'No Teachers': 'لا يوجد معلمين',

      'Public Register Number': 'رقم السجل العام',
      'UnPend Account': 'الغاء تعطيل الحساب',
      'UnPend This Account': 'الغاء تعطيل الحساب',
      'Do You Want To UnPend Account': 'هل تود الغاء تعطيل هذا الحساب',
      'Pend Account': 'تعطيل الحساب',
      'Do You Want To Pend Account': 'هل تريد تعطيل هذا الحساب مؤقتاً',
      'My Profile': 'الملف الشخصي',
      'No Phone Number yet': 'لا يوجد رقم هاتف بعد',
      'No Email yet': 'لا يوجد بريد بعد',

      'Start Time (Evening)': 'ساعة البدء المسائية',
      'End Time (Evening)': 'ساعة الانتهاء المسائية',

      'Start Time (Morning)': 'ساعة البدء الصباحية',
      'End Time (Morning)': 'ساعة الانتهاء الصباحية',

      'Select end time': 'الأمراض',
      'As-Suwayda': 'السويداء',
      'Guardian Mobile': 'رقم ولي الأمر',
      'Student Name': 'اسم الطالب',
      'Student Class': 'صف الطالب',
      'Request Date': 'تاريخ التسجيل',

      'No Lesson': 'لا توجد حصة',
      'Enroll Now': 'تسجيل الآن',
      'You Have Account ?': 'هل تملك حساب ؟',
      'No Attendance': 'لا يوجد حظور بعد',
      'Vaccines': 'اللقحات',
      'AM': 'صباحاً',
      'You have not confirmed your account yet.': 'لم تقم بتأكيد حسابك بعد',
      'Verified Now': 'التحقق الان',
      'PM': 'مساءً',
      'Rewards and Penalties': 'المكافئات و العقوبات',
      'Rewards': 'مكافئة',
      'School Content': 'محتويات المدرسة',
      'No Rewards': 'لا يوجد مكافئات',
      'No Penalty': 'لا يوجد عقوبات',
      'Penalties': 'العقوبات',
      'Attendance Today': 'حضور اليوم',
      'Employees\nAttendance': 'حضور الموظفين',
      'Students\nAttendance': 'حضور الطلاب',
      'Teachers\nAttendance': 'حضور المعلمين',
      'Percentage\nStudents': 'نسبة الطلاب',
      'Percentage\nTeacher': 'نسبة المعلمين',
      'Percentage\nEmployee': 'نسبة الموظفين',
      'Total Students': 'إجمالي الطلاب',
      'Total Teacher': 'إجمالي المعلمين',
      'Total Employee': 'إجمالي الموظفين',
      'Total Visitor': 'إجمالي الزائرين',
      'Total Books': 'إجمالي الكتب',
      'Total Division': 'إجمالي الشُعب',
      'Dashboard': 'الإحصائيات',
      'No Sessions': 'لا توجد سنوات دراسية',
      'No Grade': 'لا توجد مراحل دراسية',
      'Whatsapp Number': 'رقم الواتساب',
      'Youtube URL': 'رابط قناة اليوتيوب',
      'No data available for export': 'لا توجد بيانات للتصدير',
      'Enroll Requests': 'طلبات التسجيل',
      'Exam Table': "جدول الامتحان",
      'School Time Table': 'جدول الدوام',
      'All Students': 'كل الطلاب',
      'Study Year Students': 'طلاب العام الدراسي',
      'All Guardians': 'أولياء الأمور',
      'Student Attendance': 'حضور الطلاب',
      'Teacher Attendance': 'حضور المعلمين',
      'Manage Students Attendance': 'إدارة حضور الطلاب',
      'Teacher Management': 'إدارة المعلمين',
      'Teacher Status': 'حضور المعلمين',
      'Manage Teacher Attendance': 'إدارة حضور المعلمين',
      'Employee Management': 'إدارة الموظفين',
      'Employee Attendance': 'حضور الموظفين',
      'Manage Employee Attendance': 'إدارة حضور الموظفين',
      'Virtual User Management': 'إدارة الموظفين الافتراضيين',
      'Session Management': 'إدارة السنوات',
      'Grade Management': 'إدارة المراحل الدراسية',
      'Subject Management': 'إدارة المواد',
      'Class Management': 'إدارة الصفوف',
      'Division Management': 'إدارة الشعب',
      'Curriculum Management': 'إدارة المناهج',
      'School Data Management': 'إدارة معلومات المدرسة',
      'School Data': 'معلومات المدرسة',
      'Electronic Library': 'المكتبة الإلكترونية',
      'Transaction': 'سجل المناقلات',
      'Illness Screen': 'الأمراض',
      'Studentsss': 'من الطلاب',
      'Vaccine Screen': 'اللقاحات',
      'Presence of students': 'نسب الطلاب',
      'Presence this session students': 'نسب طلاب هذا العام',
      'Total this year': 'إجمالي هذه السنة',
      'Add': 'إضافة',
      'Request State': 'حالة الطلب',
      'Class': 'الصف',
      'Division': 'الشعبة',
      'Previous Class': 'الصف السابق',
      'Penalty En - Name': 'الاسم الإنكليزي للعقوبة',
      'Penalty Ar - Name': 'الاسم العربي للعقوبة',
      'Details': 'تفاصيل',
      'Add Penalty': 'إضافة عقوبة',
      'Delete': 'حذف',
      'Cancel': 'إلغاء',
      'Do You Want To Delete': 'هل تريد حذف العقوبة',
      'penalty': '',
      'Edit': 'تعديل',
      'Quiz Type': 'انواع الاختبارات',
      'Operation': 'العمليات',
      'Penalty Name': 'اسم العقوبة',
      'Delete Penalty': 'حذف العقوبة',
      'Edit Penalty': 'تعديل العقوبة',
      'Status': 'الحالة',
      'No Requests': 'لا يوجد طلبات',
      'Guardian Info :': 'معلومات ولي الأمر:',
      'Name :': 'الاسم:',
      'Mobile:': 'الهاتف:',
      'Email: ': 'البريد الإلكتروني: ',
      'National ID:': 'الرقم الوطني:',
      'Student Info:': 'معلومات الطالب:',
      'Current Class:': 'الصف الحالي:',
      'Previous Class:': 'الصف السابق',
      'Manage': 'إدارة',
      'Reject': 'رفض',
      'Approve': 'موافقة',
      'Rejected': 'مرفوض',
      'Pending': 'معلق',
      'Partially': 'جزئياً',
      'Search By Name': 'البحث حسب الاسم',
      'Manage Student': 'إدارة الطالب',
      'Add Exam': 'إضافة امتحان',
      'Date': 'التاريح',
      'Type': 'النوع',
      'Curriculum Name': 'اسم المنهاج',
      'Period': 'الفترة الزمنية',
      'Max Mark': 'العلامة العظمى',
      'Passing Mark': 'الحد الأدنى للنجاح',
      'Operations': 'العمليات',
      'Edit Exam': 'تعديل الامتحان',
      'Semester': 'الفصل',
      'Curriculum': 'المنهاج',
      'season': 'الفصل',
      'New Text': 'نص جديد',
      'Min Mark': 'الحد الأدنى للنجاح',
      'Time': 'الوقت',
      'You have has data in your account yet.': 'لم تتم اضافة بيانات حسابك بعد',
      'Add Data Now': 'اضافة الان',
      'Morning': 'صباحي',
      'Student Marks': 'علامات الطالب',
      'Evening': 'مسائي',
      'Not Selected': 'غير محدد',

      'Search': 'البحث',
      'Settings': 'الاعدادات',
      'Profile': 'صفحتي',
      'Personal': 'شخصي',
      'Account': 'الحساب',
      'Password': 'كلمة السر',
      'Account And Password': 'الحساب و كلمة السر',
      'Appearance': 'المظهر و اللغة',
      'Light Theme': 'النمط الفاتح',
      'Dark Theme': 'النمط الداكن',
      'Language': 'اللغة',
      'English': 'English',
      'Student Information': 'معلومات الطالب',
      'Request Information': 'معلومات الطلب',
      'Arabicc': 'العربية',
      'My Email': 'بريدي الالكتروني',
      'Edit Picture': 'تعديل الصورة',
      'Delete Picture': 'حذف الصورة',
      'Logout': 'تسجيل الخروج',
      'Bank Info': 'معلومات الحساب و الدفع',
      'Personal Information': 'معلوماتي العامة',
      'Application and Profile Settings': 'اعدادات التطبيق و الملف الشخصي',
      'Application Theem': 'نمط التطبيق',
      'Social Media Info': 'معلومات التواصل الاجتماعي',
      'Your Password': 'كلمتي السرية',
      'Old Password': 'كلمة السر القديمة',
      'Your Verification Code': 'رمز التحقق',
      'Change Password': 'تغيير كلمة السر',
      'New Password': 'كلمة السر الجديدة',
      'Confirm New Password': 'تأكيد كلمة السر الجديدة',
      'More Information': 'معلومات اضافية',
      'Technical Support': 'دعم تقني',
      'First Name': 'الاسم الأول',
      'Last Name': 'الاسم الأخير',
      'Phone Number': 'رقم الهاتف',
      'Emergency Number': 'رقم هاتف للطوارئ',
      'Join Date': 'تاريخ الانضمام',
      'Birthdate': 'تاريخ الميلاد',
      'Address': 'العنوان',
      'Current Address': 'العنوان الحالي',
      'Gender': 'الجنس',
      'My_Illness': 'امراضي',
      'My_Curr': 'موادي الدراسية',
      'My curr': 'موادي الدراسية',
      'My Illness': 'امراضي',
      'Subjects Count': 'عدد المواد',
      'Family Status': 'الحالة الأُسرية',
      'Career History': 'المسيرة المهنية',
      'Qualification': 'المؤهلات',
      'Experience': 'الخبرات',
      'Note': 'ملاحظات',
      'Facebook URL': 'رابط حساب الفيسبوك ',
      'Instagram URL': 'رابط حساب الانستغرام ',
      'X Platform URL': 'رابط حساب على منصة X',
      'Linkedin URL': 'رابط حساب اللينكد إن ',
      'Bank Name': 'اسم البنك',
      'Bank Account Title': 'اسم الحساب البنكي',
      'Bank Branch Name': 'اسم الفرع البنكي',
      'Bank Account Number': 'رقم الحساب البنكي',
      'Save': 'حفظ',
      'Username not found': 'اسم المستخدم غير موجود',
      'Find Your Account': 'العثور على حسابي',
      'Select Class First': 'اختر الصف أولاً',
      'Select Division First': 'اختر الشعبة أولاً',
      'Day': 'اليوم',
      'Teacher': 'المعلم',
      'Operation of Lessons': 'العلميات على الحصص الدراسية',
      'Sunday': 'الأحد',
      'Monday': 'الإثنين',
      'Tuesday': 'الثلاثاء',
      'Wednesday': 'الأربعاء',
      'Thursday': 'الخميس',
      'First\n Lesson': 'الحصة \n الأولى',
      'second\n Lesson': 'الحصة \n الثانية',
      'Third\n Lesson': 'الحصة \n الثالثة',
      'Forth\n Lesson': 'الحصة \n الرابعة',
      'Fifth\n Lesson': 'الحصة \n الخامسة',
      'Sixth\n Lesson': 'الحصة \n السادسة',
      'Seventh\n Lesson': 'الحصة \n السابعة',
      'Session': 'العام الدراسي',
      'Grade': 'المرحلة الدراسية',
      'Email:': 'البريد الألكتروني:',
      'Grade Level:': 'المرحلة الدراسية:',
      'Delete Students': 'حذف الطالب',
      'Studentt': '',
      'First Lesson': 'الحصة الأولى',
      'second Lesson': 'الحصة الثانية',
      'Third Lesson': 'الحصة الثالثة',
      'Forth Lesson': 'الحصة الرابعة',
      'Fifth Lesson': 'الحصة الخامسة',
      'Sixth Lesson': 'الحصة السادسة',
      'Seventh Lesson': 'الحصة السابعة',
      'No Students': 'لا يوجد طلاب',
      'Reward': 'المكافآت',
      'Penalty': 'العقوبات',
      'Start Date': 'تاريخ البداية',
      'End Date': 'تاريخ النهاية',
      'Reason': 'السبب',
      'Penalties And Rewards': 'المكافآت و العقوبات',
      'Passing': 'ناجح',
      'Failed': 'راسب',
      'Export Certificate': 'تصدير الجلاء',
      'Send': 'إرسال',
      'Logout from Current Session': 'تسجيل الخروج من الجلسة الحالية',
      'Logout from All Sessions': 'تسجيل الخروج من كافة الجلسات',
      'Penaltyy': 'عقوبة',
      'No Subjects': 'لا يوجد مواد',
      'No Content': 'لا يوجد محتويات',
      'Sessions': 'السنوات الدراسية',
      'The Reason': 'السبب',
      'Punishing Student': 'معاقبة الطالب',
      'Punishing': 'معاقبة',
      'Contact Us': 'التواصل معنا',
      'Next': 'التالي',

      'AboutUs': 'حول',
      'Stop Completion and Verification': 'ايقاف الاكمال والتحقق',
      'WhyUs': 'لماذا نحن',
      'Programs': 'دورنا',
      'Enrollment': 'التسجيل',
      'Eligibility': 'المؤهلون',

      'Back': 'رجوع',
      'Select Types:': 'حدد النوع:',
      'Selected': 'تم تحديد:',
      'Select Cell': 'حدد خلية',
      'Add Students': 'إضافة طالب',
      'Mobile Number :': 'رقم الهاتف:',
      'Select Garduans To Add Students': 'اختر ولي الأمر لإضافة طلاب',
      'Place Of Birth': 'مكان الولادة',
      'Religion': 'الدين',
      'The Verifying Code is Wrong': 'رمز التحقق غير صحيح',
      'Your password is not true , Please cheek your password and try again later':
          'كلمة المرور غير صحيحة , الرجاء التحقق منها و المعاودة مرة اخرى لاحقاً',
      'Main Page': 'الصفحة الرئيسية',
      'Blood Type': 'زمرة الدم',
      'Location': 'الموقع',
      'Full Name': 'الاسم الكامل',
      'Mobile Number': 'رقم الهاتف',
      'FamilyState': 'الحالة الأسرية',
      'National Id': 'الرقم الوطني',
      'Special need': 'ذوي احتياجات خاصة',
      'Martyr son': 'ابن شهيد',
      'Student Illness': 'أمراض الطالب',
      'Student Vaccines': 'لقاحات الطالب',
      '   Student School Info   ': '   معلومات الطالب المدرسية   ',
      'Username': 'اسم المستخدم',
      'Roll': 'الصلاحية',
      'Error Code': 'كود التحقق خاطئ',
      'Enter Verification Code Sent to:': 'ادخل رمز التحقق المرسل الى :',
      'Fee Discount': 'نسبة الخصم',
      '   Father Info   ': '   معلومات الأب   ',
      'Father Name': 'اسم الأب',
      'Father Phone': 'رقم هاتف الأب',
      'Father Work': 'عمل الأب',
      '   Mother Info   ': '   معلومات الأم   ',
      'Mother Name': 'اسم الأم',
      'Mother Phone': 'رقم هاتف الأم',
      'Mother Work': 'عمل الأم',
      '   More Info   ': '   معلومات أخرى   ',
      'Last School Details': 'تفاصيل المدرسة السابقة',
      '   File Data   ': '   بيانات الملفات   ',
      'Add Father Passport': 'إضافة جواز سفر الأب',
      'File Father Passport Dropped!': 'جواز سفر الأب تم لصقه',
      'Add Mother Passport': 'إضافة جواز سفر الأم',
      'File Mother Passport Dropped!': 'جواز سفر الأم تم لصقه',
      'Add Son Passport': 'إضافة جواز سفر الابن',
      'File Son Passport Dropped!': 'جواز سفر الابن تم لصقه',
      'Add ID File': 'إضافة ملف التعريف الشخصي',
      'File Id Dropped!': 'ملف التعريف تم لصقه',
      'Add Certificate': 'إضافة شهادة',
      'File Certificate Dropped!': 'الشهادة تم لصقها',
      'Add Academic sequence': 'إضافة تسلسل أكاديمي',
      'File Academic sequence Dropped!': 'التسلسل الأكديمي تم لصقه',
      'Add Family notebook': 'إضافة دفتر العائلة',
      'File Family notebook Dropped!': 'دفتر العائلة تم لصقه',
      "Local ID": "رقم التعريف الشخصي المحلي",
      'Male': 'ذكر',
      'Female': 'أنثى',
      'Muslim': 'مسلم',
      'Christian': 'مسيحي',
      'Widow': 'أرمل',
      'Single': 'أعزب',
      'Syria': 'سوريا',
      "No Address yet": "لا يوجد عنوان بعد",
      'Married': 'متزوج',
      'Divorced': 'مطلق',
      'Click To Add Father Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الأب\nأو\nاسحب وأفلت الملف هنا',
      'Done Selected File': 'تم اختيار الملف',
      'Click To Add Mother Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الأم\nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Son Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الابن\nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Id\nOr\nDrag And Drop File Here':
          'اضغط لإضافة ملف التعريف الشخصي  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Certificate\nOr\nDrag And Drop File Here':
          'اضغط لإضافة شهادة  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Academic sequence\nOr\nDrag And Drop File Here':
          'اضغط لإضافة تسلسل أكديمي  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Family notebook\nOr\nDrag And Drop File Here':
          'اضغط لإضافة دفتر العائلة  \nأو\nاسحب وأفلت الملف هنا',
      'Student illeness': 'أمراض الطالب',
      'Done': "تم",
      'Classes': "الصفوف",
      'Divisions': "الشعب",
      'Quiz Types': "انواع الاختبارات",
      'Report Card Settings': "اعدادات الجلاء",
      'Add Picture': "اضافة صورة",
      'Complete the registration details before starting':
          "استكمال بيانات التسجيل قبل البدء",
      'Student Vaccine': "لقاحات الطالب",
      'Add Your Photo Profile': "اضف صورة ملفك الشخصي",

      /////////////////////////////////section 1 and home appbar////////////////////////

      'WE CARE ABOUT \n YOUR FUTURE': 'نحن نهتم\n بمستقبلك',
      'WE CARE ABOUT YOUR FUTURE': 'نحن نهتم بمستقبلك',
      'Join us to enter a better world filled with advanced educational methods through Virtual Modern School':
          'انضم إلينا لدخول عالم أفضل مليء بالأساليب التعليمية المتطورة من خلال المدرسة الافتراضية الحديثة',
      'Enroll': 'تسجيل',
      'Sign In': 'تسجيل دخول',
      'Teachers': 'المعلمين',
      'Students': 'الطلاب',
      'Visitors': 'الزائرين',

      'IP Address': 'عنوان ال IP',
      'Platform': 'نظام التشغيل',
      'Browser Version': 'اصدار المتصفح',
      'Device Type': 'نوع الجهاز',
      'Device': 'الجهاز',
      'Action': 'المهمة',
      'Detail': 'تفاصيل',
      'admin': 'ادمن',
      'teacher': 'مدرس',
      'guardian': 'ولي أمر',
      'student': 'طالب',
      'Vaccine': 'كل اللقاحات',
      'illness': 'كل الأمراض',

/////////////////////////////////////section 2///////////////////////////////
      'Who Can Register At Virtual Modern School':
          'من يمكنهم التسجيل في المدرسة الافتراضية الحديثة',
      'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary':
          'يمكن لأي شخص يقيم خارج سوريا ويرغب في دراسة المناهج التعليمية السورية من المرحلة  ',
      'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted':
          'الابتدائية إلى المرحلة المتوسطة والثانوية التسجيل والتخرج للحصول على شهادة ',
      'by the Ministry of Education at Syrian Arab Republic':
          'الثانوية العامة المقدمة من وزارة التربية في الجمهورية العربية السورية',
      'People with special needs who are residing in Syria are uncapable to study in regular schools uncapable':
          'الأشخاص ذوو الاحتياجات الخاصة المقيمون في سوريا غير قادرين على الدراسة في ',
      'to study uncapable to study in regular schools and exceptional students cases determined by the':
          'المدارس العادية وحالات الطلاب الاستثنائيين التي تحددها وزارة التربية والتعليم',
      'Ministry of Education at Syrian Arab Diploma granted by the Ministry of Education at Syrian Arab':
          'بالدبلوم العربي السوري الممنوح من وزارة التربية في الجمهورية العربية السورية',
      'Republic': '',

      //////////////////////////section 3////////////////////////////
      'How I Can Enroll At Virtual Modern School':
          'كيف يمكنني التسجيل في المدرسة الافتراضية الحديثة',
      'Parents of our students can register their children in the Virtual Modern School':
          'يمكن لأولياء أمور طلابنا تسجيل أبنائهم في المدرسة الافتراضية الحديثة',
      'by the following steps:': 'بالخطوات التالية:',
      '1. Enter the first and last name of the guardian':
          '1. أدخل الاسم الأول والأخير لوَليّ الأمر',
      '2. Enter the mobile phone number of guardian':
          '2. أدخل رقم الهاتف المحمول لوَليّ الأمر ',
      '3. Enter the Syrian national number of the guardian':
          '3. أدخل الرقم القومي السوري لوَليّ الأمر',
      'Read More': 'قراءة المزيد',

      ////////////////////////////////////section 4////////////////////////////////
      'Why Us?': 'لماذا نحن',
      'Virtual Modern School is an online learning platform that helps students to learn the':
          'المدرسة الافتراضية الحديثة هي منصة تعليمية عبر الإنترنت تساعد الطلاب على  ',
      'Syrian Education Curriculum from home. The courses of this platform are designed':
          'تعلم المنهج التعليمي السوري من المنزل. تم تصميم الدورات في هذه المنصة للمدرسة الابتدائية،',
      'for elementary school, middle school, and high school all in one place.':
          'والمدرسة المتوسطة، والمدرسة الثانوية في مكان واحد.',

      'Improving educational': 'تحسين مهارات',
      'Skills': 'التعليم',
      'Smart virtual': 'اجتماع افتراضي',
      'meeting': 'ذكي',
      'Outstanding': 'سهولة التعامل ',
      'user - friendliness': 'مع المستخدم',
      'Instant live': 'دروس مباشرة ',
      'Lessons': 'فورية',
      'Focus on results': 'التركيز على النتائج الاساسية',
      'Multiple registration': 'خيارات تسجيل',
      'options': 'متعددة',
      ///////////////////////////////////section 5//////////////////////////////////////

      'Who Are We': 'من نحن',
      'is a community of learners, including students, parents, and staff, dedicated to creating a rigorous and':
          'المدرسة الافتراضية الحديثة هي مجتمع من المتعلمين ، بما في ذلك الطلاب وأولياء الأمور والموظفين ، مكرسين لإنشاء بيئة صارمة',
      'VIRTUAL MODERN SCHOOL (VMS)': '',
      'inclusive educational environment. VMS students are goal-oriented, critical thinkers, and community leaders':
          ' و بيئة تعليمية شاملة. طلاب المدرسة هادفون ومفكرين نقديين وقادة مجتمع ملتزمون ',
      'committed to achieving high levels of integrity and academic success.':
          'بتحقيق مستويات عالية من النزاهة والنجاح الأكاديمي.',

      'VIRTUAL MODERN SCHOOL (VMS) staff aim to create a supportive':
          'يهدف موظفو المدرسة الافتراضية الحديثة إلى خلق بيئة داعمة وتحديّة',
      'and challenging environment for all students to reach their potential,':
          'لجميع الطلاب للوصول إلى إمكاناتهم، والانخراط في ',
      'engaging in continuous improvement through goal setting and':
          ' تحسين مستمر من خلال تحديد الأهداف والتأمل',
      'reflection': '',
      'Virtual Modern School': 'المدرسة الافتراضية الحديثة ',

      ////////////////////////section 6//////////////////////////

      'What Do We Do': 'ماذا نفعل',
      'We develop a culture of excellence that includes a robust instructional program aligned to the':
          'نحن نطور ثقافة التميز التي تشمل برنامجًا تعليميًا قويًا يتوافق مع أعلى المعايير،',
      'highest standards with a focus on implementing balanced literacy through reading and writing':
          'مع التركيز على تطبيق التعليم المميز من خلال ورش عمل القراءة والكتابة،',
      'workshops, while cultivating competency across all subject areas.':
          'من خلال تعزيز الكفاءة في جميع المواد الدراسية.',
      'We are committed to developing well-rounded students who embody our core values: Be Safe, Be Respectful, Be Responsible, and Be Mindful. Our vibrant learning environment encourages discovery and creative expression, making every student feel valued.\n\nWe provide our educators with robust professional development to enhance teaching practices and boost student success. Through collaboration and a community schools model, we align resources to ensure every student thrives. Join us in our journey towards excellence!':
          'نحن ملتزمون بتطوير طلاب متوازنين يجسدون قيمنا الأساسية: كن آمناً، وكن محترماً، وكن مسؤولا، وكن واعياً. تشجع بيئة التعلم الحيوية لدينا على الاكتشاف والتعبير الإبداعي، مما يجعل كل طالب يشعر بالتقدير.\n\n نحن نقدم لمعلمينا تطويراً مهنياً قوياً لتعزيز ممارسات التدريس وزيادة نجاح الطلاب. من خلال التعاون ونموذج المدارس المجتمعية، نقوم بتنسيق الموارد لضمان ازدهار كل طالب.\n\n انضم إلينا في رحلتنا نحو التميز!',
      //////////////////////////////////section 7////////////////////////////////////////
      'Openning Hours': 'ساعات العمل',
      '8 AM -----> 1 PM': '8 صباحاً---------> 1 ظهراً',
      '3 PM -----> 8 PM': '3 ظهراً--------->8 مساءً',
      'Contact Details': 'معلومات التواصل',
      'Shakib Arslan Street - Engineers Syndicate Building - 2nd Floor - AlSuwaidaa - Syria':
          'سوريا - السويداء -شارع شكيب أرسلان - مجمع المهندسيين - الطابق الثاني',
      'All Rights reserved. Copyright': 'جميع الحقوق محفوظة. حقوق النشر',
      //////////////////////////////

      'Login': 'تسجيل الدخول',

      'Update Student': 'تحديث الطالب',
      'Pend Student': 'تعطيل الحساب',
      'Do You Want To Pend ': 'هل تريد تعطيل حساب الطالب',
      'Student?': '',
      'Yes': 'نعم',
      'No': 'لا',
      'UnPend Student': 'إلفاء تعطيل الحساب',
      'Do You Want To UnPend': 'هل تريد إلفاء تعطيل الحساب',
      'UnPend This Student': 'إلغاء تعطيل حساب هذا الطالب',
      'Realagon': 'الدين',
      'Family State': 'الحالة الأسرية',
      'Last School Detail': 'معلومات المدرسة السابقة',
      'Edit Student': 'تعديل الطالب',
      'Edite': 'تعديل معلومات',
      'Info': '',

      'Show only selected items': 'عرض العناصر المختارة فقط',
      'Do You Want To Deletee': 'هل تريد حذف الطالب ',
      'No Result': 'لا يوجد نتيجة',
      'Guardian Name': 'اسم ولي الأمر',
      'Guardian National ID': 'الرقم الوطني لوَليّ الأمر',
      'Guardian Email': ' البريد الإلكتروني لوَليّ الأمر ',
      'Guardian Phone Number': 'رقم هاتف لوَليّ الأمر',
      'Edit Guardian': 'تعديل الوَليّ الأمر',
      'Confirm Password': 'تأكيد كلمة السر',
      'Add Guardian': 'إضافة وليّ الأمر',

      'Email': 'البريد الإلكتروني',
      'Guardian Username': 'اسم المستخدم لوَليّ الأمر',
      'Name': 'الاسم',
      'Arabic Address': 'العنوان بالعربية',
      'English Address': 'العنوان بالانكليزية',
      'English Village': 'القرية بالانكليزية',
      'Arabic Village': 'القرية بالعربية',
      'Morning Time': 'الدوام الصباحي',
      'Evening Time': 'الدوام المسائي',
      'phone Number': 'رقم الهاتف ',
      'National ID': 'الرقم الوطني',

      'Set All As a Holiday': 'وضع عطلة للكل',
      'Cause': 'السبب',
      'Enter The Reason For Absence': 'أدخل سبب الغياب',
      'The reason for the absence of the all students': 'سبب غياب جميع الطلاب',
      'Present': 'حاضر',
      'Truant': 'غائب',
      'Late': 'متأخر',
      'Holiday': 'عطلة',
      'The reason for the absence of the student': 'سبب غياب الطالب',
      'Attendance Today Has Been Uploaded': 'الحضور رفع اليوم',
      'Attendence': '',
      "att": "حضور",
      'Subject': 'المادة',
      'Add Teacher': 'إضافة معلم',
      'Contract Type': 'نوع العقد',
      'Full Time': 'دوام كامل',
      'hours': 'ساعات',
      'Hours': 'ساعات',
      'This Teacher Does Not Contain Any Data': 'هذا المعلم ليس لديه أي بيانات',
      'Mobile: ': 'الهاتف: ',
      'Teacherr': '',
      'Do You Want To Deletet': 'هل تريد حذف المعلم',
      'Delete Teacher': 'حذف المعلم',
      'If You Deselected The Illness The File Will Remove':
          'إذا أردت إلغاء تحديد المرض , سوف يحذف الملف',
      'If You Click Yes The File Will Remove': 'إذا ضغطت نعم , الملف سوف يحذف',
      'illness File': 'ملف مرض',
      'Vaccine File': 'ملف لقاح',
      'Employee Illness': 'أمراض الموظف',
      'Teacher Illness': 'أمراض المعلم',
      'The reason for the absence of the all Teachers': 'سبب غياب كل المعلمين',
      'Vacation': 'إجازة',
      "sub": "مواد",
      "No Guardian": "لا يوجد أولياء أمور",
      'Subjectssss': 'المواد',
      'Subjects': '',
      'Rewards Students': 'مكافئة الطالب',
      'Rewards & Penalties': 'مكافئات و عقوبات',
      'My Account': 'حسابي',

      'Job Title': 'المسمى الوظيفي',
      "Manager": "مدير المدرسة",
      "Dustman": "عامل نظافة",
      "Guard": "حارس",
      "My Attendance": "حظوري",
      "Show Approve Files": "عرض ملفات القبول",
      "Registration": "مدير قسم التسجيل",
      "Secretariat": "أمين السر",
      "Secretary": "سكرتير",
      "Supervisor": "مشرف",
      "Accountant": "محاسب",
      "Media": "إعلامي",
      "Technical Support Manager": "مدير الدعم التقني",
      'Add Employee': 'إضافة موظف',
      'Add Full Employee': 'إضافة موظف كامل',
      'Observer': 'مراقب',
      'Admin': "مدير ",
      'Sub Admin': "مساعد مدير ",
      "Salary": "الراتب",
      "Employee": "الموضفين",
      'Employee Bank Info': 'معلومات الحساب البنكي للموظف',
      'IFSC Code': 'شيفرة IFSC',
      'This Employee Does Not Contain Any Data':
          'هذا الموظف ليس لديه أي بيانات',
      'Employeey': '',
      'Do You Want To Deletey': 'هل تريد حذف الموظف',
      'Delete Employee': 'حذف الموظف',
      'No Employees': 'لا يوجد موظفين',
      'Edit Employee': 'تعديل الموظف',
      'The reason for the absence of the all employee':
          'سبب غياب جميع الموظفين',
      'The reason for the absence of the employee': 'سبب غياب الموظف',
      'Add Virtual User': 'إضافة موظف افتراضي',
      'No Virtual User': 'لا يوجد مزظفين افتراضيين',
      'Do You Want To Deletec': 'هل تريد حذف الموظف الافتراضي',
      'Virtual User': '',
      'Virtual Employee': 'الموضفين الافتراضيين',
      'observer': "مراقب",
      "class": "صف",
      "Degree": "الدرجة",
      "Students Marks in": "علامات الطلاب في مادة",
      "State": "الحالة",
      'Class En - Name': 'الاسم الإنكليزي للصف',
      'Class Ar - Name': 'الاسم العربي للصف',
      'Admin Account': 'حساب مدير',
      'No selected curriculum': 'لا يوجد مناهج مختارة',
      'Drive URL': 'رابط الـ Drive',
      'Add Class': 'إضافة صف',
      'Grade En - Name': 'الاسم الإنكليزي للمرحلة الدراسية',
      'Grade Ar - Name': 'الاسم العربي للمرحلة الدراسية',
      'Curriculums': 'المناهج',
      'Edit Class': 'تعديل الصف',
      'Classs': "",
      'No Time yet': "لم يحدد وقت",
      'Not yet evaluated': "غير مقيم",
      'Do You Want To Deleteclass': 'هل تريد حذف الصف',
      'Delete Class': 'حذف الصف',
      'No Classes': 'لا يوجد صفوف',
      'Curriculum English Name': 'الاسم الإنكليزي للمنهاج',
      'Failed subject': 'منهاج مرسب',
      'Is Failed subject': 'هل  المنهاج مرسب',
      'Add Curriculum': 'إضافة منهاج',

      'Please select true value': 'يرجى اختيار قيمة صحيحة',
      'Click To Add File\nOr\nDrag And Drop File Here':
          'اضغط لإضافة ملف \n أو \n اسحب و افلت الملف هنا',
      'Click To Add Image\nOr\nDrag And Drop Image Here':
          'اضغط لإضافة صورة \n أو \n اسحب و افلت الصورة هنا',
      'Done Selected Image': 'تم اختيار الصورة',
      "The First Semester": "الفصل الأول",
      "The Second Semester": "الفصل الثاني",
      "The Third Semester": "الفصل الثالث",
      'Max Mark :': 'العلامة العظمى :',
      'Passing Mark :': 'علامة النجاح :',
      'Is Failure Agent :': 'هل المنهاج مرسب:',
      'Do You Want To Deletecur': 'هل تريد حذف المادة',
      'Curriculumm': '',
      'Delete Curriculum': 'حذف المادة',
      'No Curriculum': 'لا يوجد مناهج',

      'PDF File Successfully Dropped!': 'تم لصق الملف بنجاح',
      'Error: Unsupported File Type.': 'خطأ : نوع الملف غير مدعوم',
      'Error: Only One File Is Allowed.': 'خطأ : فقط ملف واحد مسموح',
      'Add Book': 'إضافة كتاب',
      'Add Electronic Book': 'إضافة كتاب إلكتروني',
      'English Name': "الاسم الإنكليزي",

      'Do You Want To Deletebook': 'هل تريد حذف الكتاب',
      'Book': '',
      'Delete Electronic Book': 'حذف الكتاب الإلكتروني',
      'No Electronic Book': 'لا يوجد كتب إلكترونية',

      'Fee Count': 'الاشتراك السنوي',
      'Add Grade': 'إضافة مرحلة دراسية',
      'Grade Name': 'اسم المرحلة الدراسية',
      'Do You Want To Deletegarde': 'هل تريد حذف المرحلة الدراسية',
      'Gradee': '',
      'Delete Grade': 'حذف المرحلة الدراسية',
      'Edit Grade': 'تعديل المرحلة الدراسية',
      'Is chronic : Yes': 'مزمن : نعم',
      'Is chronic : No': 'مزمن : لا',
      'Illnesss': '',
      'Do You Want To Deleteill': 'هل تريد حذف المرض',
      'Delete Illness': 'حذف المرض',
      'No Illness': 'لا يوجد أمراض',
      'Is Chronic': 'هل هو مزمن',
      'Add Illness': 'إضافة مرض',
      'Division En - Name': 'الاسم الإنكليزي للشعبة',
      'Division Ar - Name': 'الاسم العربي للشعبة',
      'Meet URL': 'رابط اجتماع الشعبة',
      'Add Division': 'إضافة شعبة',
      'Edit Division': 'تعديل الشعبة',
      'Do You Want To Deletediv': 'هل تريد حذف الشعبة',
      'Divisionn': '',
      'Delete Division': 'حذف الشعبة',
      'No Divisions': 'لا يوجد شُعب',

      'School Name': 'اسم المدرسة',
      'License Number': 'رقم الترخيص',
      'Village': 'القرية',
      'Region': 'المنطقة',
      'Phone': 'رقم الهاتف',
      'Work Begin Year': 'سنة بدأ العمل',
      'Creation Year': 'سنة الإنشاء',
      'Fax': 'الفاكس',
      "Country": "البلد",

      'Clinic Name': 'اسم العيادة',
      'Congregation number': 'رقم المجمع',
      'Previous name': 'الاسم السابق',
      'Town Chip': 'الناحية',
      'Outstanding School': 'مدرسة متميزين',
      'Taken Over School': 'المدرسة مستولى عليها',
      'Reassignment Teachers': 'إعادة تعيين المعلمين',
      'Martyrs Sons': 'أبناء الشهداء',
      'Internet Connection': 'اتصال بالإنترنت',
      'Government Connection': 'الاتصال الحكومي',
      'Joint Building': 'مبنى مشترك',
      'Industrial Section': 'قسم صناعي',

      'Study Year': 'السنة الدراسية',
      'Enter Year': 'أدخل السنة',
      'Year': 'السنة',
      'Add Session': 'إضافة سنة دراسية',
      'Yes Close': 'نعم أغلق',
      'Closed': 'مغلق',
      'Close Session': 'إغلاق السنة الدراسية',
      'Close': 'إغلاق',
      'Start Date :': 'تاريخ البداية : ',
      'End Date :': 'تاريخ النهاية : ',
      'Do You Want To Deletess': 'هل تريد حذف السنة الدراسية',
      'Sessionn': '',
      'Delete Session': 'حذف سنة دراسية',
      'Edit Session': 'تعديل السنة',
      'Opened': 'مفتوح',
      'Subject En - Name': 'الاسم الإنكليزي للمادة',
      'Subject Ar - Name': 'الاسم العربي للمادة',
      'Add Subject': 'إضافة مادة',
      'Subject Name': 'اسم المادة',
      'Do You Want To Deletesub': 'هل تريد حذف المادة',
      'Subjectt': '',
      'Delete Subject': 'حذف المادة',
      'Edit Subject': 'تعديل المادة',
      'Role': 'الدور',
      'Schedules': 'الجداول',
      'Employees': 'الموظفين',
      'Management': 'إدارية',
      'General': 'عامة',
      'SubAdmin': 'مساعد مدير',
      'Guardian': 'وليّ أمر',
      'Student': 'طالب',
      'Up 200': 'أكثر من 200',
      'Device Info': 'معلومات الجهاز',
      'Add Vaccine': 'إضافة لقاح',
      'Location :': 'الموقع: ',
      'Vaccinee': '',
      'Do You Want To Deletevac': 'هل تريد حذف اللقاح',
      'Delete Vaccine': 'حذف اللقاح',
      'No Vaccine': 'لا يوجد لقاحات',
      'No Data in Exam Table': 'لا يوجد بيانات في جدول الامتحان',
      'Tools': 'الأدوات',
      'Add Text': 'إضافة نص',
      'Export As Pdf': 'التصدير كـ PDF',
      'Edit text': 'تعديل النص',
      'Enter text': 'أدخل نص',
      'Font Size: ': 'حجم الخط: ',
      'Add Marks For All': 'إضافة علامة للكل',
      'Students Marks': 'علامات الطلاب',
      'Selected Class': 'اختر صف',
      'Selected Division': 'اختر شعبة',
      'Selected Curriculum': 'اختر منهاج',
      'No Quiz Type': 'لا يوجد أنواع اختبارات',
      'Group Name': 'اسم المجموعة',
      'ratio': 'النسبة',
      'Group Items': 'عناصر المجموعة',
      'Item ratio': 'نسبة العنصر',
      'Item Name': 'اسم العنصر',
      'Add Group': 'إضافة مجموعة',
      'Add a New Group': 'إضافة مجموعة جديدة',
      'Is Quizable': 'قابلية إجراء اختبار',
      'Add Item': 'إضافة عنصر',
      'Add Group Item': 'إضافة عنصر مجموعة',
      'Edit Item': 'تعديل عنصر',
      'Edit Group Item': 'تعديل عنصر مجموعة',
      'Rerange': 'إعادة ترتيب',
      'Rerange Group': 'إعادة ترتيب المجموعة',
      'Confirm Delete': 'تأكيد الحذف',
      'Are you sure you want to delete this group?':
          'هل أنت متأكد من أنك تريد حذف هذه المجموعة',
      'Edit Group': 'تعديل مجموعة',
      'Editgroup': 'تعديل المجموعة',
      'Groupp': '',
      'Please Select Class First': 'يرجى اختر الصف أولاً',
      'Select Type': 'اختر النوع',
      'Type Operations': 'العمليات على النوع',
      'No types available': 'لا يتوفر أنواع',
      'Selected:': 'مختار:',
      'Sum': 'مجموع',
      'Average': 'متوسط',
      'Edit Teacher': 'تعديل المعلم',
      'Teacher Bank Info': 'معلومات الحساب البنكي للمعلم',
      'FullTime': 'دوام كامل',

      'Curriculum English Name - English Class Name':
          'الاسم الإنكليزي للمنهاج - الاسم الإنكليزي للصف',
      'Curriculum Name - Class Name': 'اسم المنهاج - اسم الصف',
      'Curriculum List': 'قائمة المناهج',
      'Content En Name': 'الاسم الإنكليزي للمحتوى',
      'Content Name': 'اسم المحتوى',
      'Add Content': 'إضافة محتوى',
      'Edit Content': 'تعديل المحتوى',

      'This Subjact has Curriculums': 'هذه المادة تحتوي على مناهج',
      'You Can`t Delete This Subject': 'لا يمكنك حذف هذه المادة',
      'Ratio': 'النسبة',
      'StudyShare Table': 'جدول الدوام',
      'Attendences': 'الحضور',
      'StudyShare table': 'جدول الدوام',
      'Father Passport': 'جواز سفر الأب',
      'Mother Passport': 'جواز سفر الأم',
      'Son Passport': 'جواز سفر الابن',
      'ID File': 'ID الـ الملف',
      'Certificate': 'الشهادات',
      'Academic sequence': 'التسلسل الأكديمي',
      'Family notebook': 'دفتر العائلة',
      'Add Rewards': 'إضافة مكافأة',
      'Do You Want To DeleteeAtt': 'هل تريد حذف حضور',
      'Attendenceatt': '',
      'Delete Attendence': 'حذف حضور',
      'you can not close this session': 'لا يمكنك إغلاق هذه السنة الدراسية',
      'Re-order': 'إعادة الطلب',
      'Import': 'استيراد',
      'Marks': 'العلامات',
      'Show Files': 'عرض الملفات',
      'Select Session': 'اختر الفصل',
      'Move From Session': 'استيراد من فصل',
      'LMS Platform': 'المنصة التعليمية',
      'Homework': 'الوظائف',
      'File Homework': 'وظيفة ملف',
      'Questions Homework': 'وظيفة أسئلة',
    },
    'en': {
      'Welcome Laith Haitham Azzam': 'Welcome Laith Haitham Azzam',
      'Have A Nice Day At Work': 'Have A Nice Day At Work',
      'Illness and Vaccines': 'Illness and Vaccines',
      'Illness': 'Illness',
      'No Lesson': 'No Lesson',
      'No Guardian': 'No Guardian',
      'Rewards Students': 'Rewards Students',
      'Rewards & Penalties': 'Rewards & Penalties',
      'Vaccines': 'Vaccines',
      'Rewards and Penalties': 'Rewards and Penalties',
      'Rewards': 'Rewards',
      'Penalties': 'Penalties',
      'Attendance Today': 'Attendance Today',
      'Employees\nAttendance': 'Employees\nAttendance',
      'Students\nAttendance': 'Students\nAttendance',
      'Teachers\nAttendance': 'Teachers\nAttendance',
      'Percentage\nStudents': 'Percentage\nStudents',
      'Percentage\nTeacher': 'Percentage\nTeacher',
      'Percentage\nEmployee': 'Percentage\nEmployee',
      'Total Students': 'Total Students',
      'Total Teacher': 'Total Teacher',
      'Total Employee': 'Total Employee',
      'Total Visitor': 'Total Visitor',
      'Total Books': 'Total Books',
      'Total Division': 'Total Division',
      'Dashboard': 'Dashboard',
      'No data available for export': 'No data available for export',
      'Request State': 'Request State',
      'Complete the registration details before starting':
          'Complete the registration details before starting',
      'Enroll Requests': 'Enroll Requests',
      'Exam Table': "Exam Table",
      'Virtual Employee': "Virtual Employee",
      'School Time Table': 'School Time Table',
      'All Students': 'All Students',
      'Study Year Students': 'Study Year Students',
      'All Guardians': 'All Guardians',
      'Student Attendance': 'Student Attendance',
      'Teacher Attendance': 'Teacher Attendance',
      'Manage Students Attendance': 'Manage Students Attendance',
      'Teacher Management': 'Teacher Management',
      'Teacher Status': 'Teacher Status',
      'Manage Teacher Attendance': 'Manage Teacher Attendance',
      'Employee Management': 'Employee Management',
      'Employee Attendance': 'Employee Attendance',
      'Manage Employee Attendance': 'Manage Employee Attendance',
      'Virtual User Management': 'Virtual User Management',
      'Session Management': 'Session Management',
      'Grade Management': 'Grade Management',
      'Subject Management': 'Subject Management',
      'Class Management': 'Class Management',
      'Division Management': 'Division Management',
      'Curriculum Management': 'Curriculum Management',
      'School Data Management': 'School Data Management',
      'School Data': 'School Data',
      'Electronic Library': 'Electronic Library',
      'Transaction': 'Transaction',
      'My Profile': 'My Profile',
      'No Email yet': 'No Email yet',
      'No Phone Number yet': 'No Phone Number yet',
      'My Email': 'My Email',
      'Illness Screen': 'Illness Screen',
      'Vaccine Screen': 'Vaccine Screen',
      'Presence of students': 'Presence of students',
      'Presence this session students': 'Presence 2024 students',
      'Total this year': 'Total this year',
      'Add': 'Add',
      'Previous Class': 'Previous Class',
      'Stop Completion and Verification': 'Stop Completion and Verification',
      'Penalty En - Name': 'Penalty En - Name',
      'Penalty Ar - Name': 'Penalty Ar - Name',
      'Details': 'Details',
      'Add Penalty': 'Add Penalty',
      'Delete': 'Delete',
      'Cancel': 'Cancel',
      'Old Password': 'Old Password',
      'Do You Want To Delete': 'Do You Want To Delete',
      'penalty': 'penalty',
      'Edit': 'Edit',
      'No Attendance': 'No Attendance',
      'Operation': 'Operation',
      'Penalty Name': 'Penalty Name',
      'Delete Penalty': 'Delete Penalty',
      'Edit Penalty': 'Edit Penalty',
      'Status': 'Status',
      'No Requests': 'No Requests',
      'Guardian Info :': 'Guardian Info :',
      'Name :': 'Name :',
      'Student Information': 'Student Information',
      'Request Information:': 'Request Information:',
      'Mobile:': 'Mobile:',
      'Email: ': 'Email: ',
      'National ID:': 'National ID:',
      'Student Info:': 'Student Info:',
      'Current Class:': 'Current Class:',
      'Previous Class:': 'Previous Class',
      'Manage': 'Manage',
      'Schedules': 'Schedules',
      'Employees': 'Employees',
      'Management': 'Management',
      'General': 'General',
      'Reject': 'Reject',
      'Approve': 'Approve',
      'Rejected': 'Rejected',
      'Pending': 'Pending',
      'Partially': 'Partially',
      'Search By Name': 'Search By Name',
      'Class': 'Class',
      'Division': 'Division',
      'Manage Student': 'Manage Student',
      'Add Exam': 'Add Exam',
      'Date': 'Date',
      'Type': 'Type',
      'Quiz Type': 'Quiz Type',
      'No Rewards': 'No Rewards',
      'No Penalty': 'No Penalty',
      'Curriculum Name': 'Curriculum Name',
      'Period': 'Period',
      'Max Mark': 'Max Mark',
      'Passing Mark': 'Passing Mark',
      'Operations': 'Operations',
      'Edit Exam': 'Edit Exam',
      'Semester': 'Semester',
      'Curriculum': 'Curriculum',
      'season': 'semester',
      'New Text': 'New Text',
      'Min Mark': 'Min Mark',
      'Time': 'Time',
      'Morning': 'Morning',
      'Evening': 'Evening',

      'Search': 'Search',
      'Settings': 'Settings',
      'Profile': 'Profile',
      'Personal': 'Personal',
      'Account': 'Account',
      'Password': 'Password',
      'Appearance': 'Appearance and Language',
      'Light Theme': 'Light Theme',
      'Dark Theme': 'Dark Theme',
      'Language': 'Language',
      'English': 'English',
      'Arabicc': 'العربية',
      'Logout': 'Logout',
      'Logout from Current Session': 'Logout from Current Session',
      'Logout from All Sessions': 'Logout from All Sessions',
      'Sessions': 'Sessions',
      'Edit Picture': 'Edit Picture',
      'Delete Picture': 'Delete Picture',
      'Application Theem': 'Application Theme',
      'Application and Profile Settings': 'Application and Profile Settings',
      'Personal Information': 'My General Details',
      'Social Media Info': 'Social Media Info',
      'Bank Info': 'Bank Info',
      'Account And Password': 'Account And Password',
      'Your Password': 'Your Password',
      'Your Verification Code': 'Your Verification Code',
      'Change Password': 'Change Password',
      'New Password': 'New Password',
      'Confirm New Password': 'Confirm New Password',
      'More Information': 'More Information',
      'First Name': 'First Name',
      'Last Name': 'Last Name',
      'Phone Number': 'Phone Number',
      'Emergency Number': 'Emergency Number',
      'Join Date': 'Join Date',
      'Birthdate': 'Birthdate',
      'Address': 'Address',
      'Current Address': 'Current Address',
      'Gender': 'Gender',
      'Subjects Count': 'Subjects Count',
      'Family Status': 'Family Status',
      'Career History': 'Career History',
      'Qualification': 'Qualification',
      'Experience': 'Experience',
      'Note': 'Note',
      'Save': 'Save',
      'Next': 'Next',
      'Facebook URL': 'Facebook URL',
      'Instagram URL': 'Instagram URL',
      'X Platform URL': 'X Platform URL',
      'Linkedin URL': 'Linkedin URL',
      'Bank Name': 'Bank Name',
      'Bank Account Title': 'Bank Account Title',
      'Bank Branch Name': 'Bank Branch Name',
      'Bank Account Number': 'Bank Account Number',
      'Select Class First': 'Select Class First',
      'Select Division First': 'Select Division First',
      'Day': 'Day',
      'Add Your Photo Profile': 'Add Your Photo Profile',
      'Teacher': 'Teacher',
      'Operation of Lessons': 'Operation of Lessons',
      'Sunday': 'Sunday',
      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'First\n Lesson': 'First\n Lesson',
      'second\n Lesson': 'second\n Lesson',
      'Third\n Lesson': 'Third\n Lesson',
      'Forth\n Lesson': 'Forth\n Lesson',
      'Fifth\n Lesson': 'Fifth\n Lesson',
      'Sixth\n Lesson': 'Sixth\n Lesson',
      'Seventh\n Lesson': 'Seventh\n Lesson',
      'Session': 'Session',
      'Grade': 'Grade',
      'Email:': 'Email:',
      'Grade Level:': 'Grade Level:',
      'Delete Students': 'Delete Student',
      'Student': 'Student',
      'No Students': 'No Students',
      'Reward': 'Reward',
      'Penalty': 'Penalty',
      'Start Date': 'Start Date',
      'End Date': 'End Date',
      'Reason': 'Reason',
      'School Content': 'School Content',
      'Penalties And Rewards': 'Penalties And Rewards',
      'Passing': 'Passing',
      'Failed': 'Failed',
      'Export Certificate': 'Export Certificate',
      'Send': 'Send',
      'Penaltyy': 'Penalty',
      'The Reason': 'The Reason',
      'Punishing Student': 'Punishing Student',
      'Punishing': 'Punishing',
      'Contact Us': 'Contact Us',
      'AboutUs': 'AboutUs',
      'WhyUs': 'WhyUs',
      'Programs': 'Our Role',
      'Forgot your password  ?': 'Forgot your password  ?',
      'Enrollment': 'Enrollment',
      'Eligibility': 'Eligibility',
      'Who Can Register At Virtual Modern School':
          'Who Can Register At Virtual Modern School',
      'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary':
          'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary',
      'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted':
          'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted',
      'by the Ministry of Education at Syrian Arab Republic':
          'by the Ministry of Education at Syrian Arab Republic',
      'Back': 'Back',
      'Selected': 'Selected',
      'Select Types:': 'Select Types:',
      'Select Cell': 'Select Cell',
      'Add Students': 'Add Students',
      'Mobile Number :': 'Mobile Number :',
      'Select Garduans To Add Students': 'Select Garduans To Add Students',
      'Place Of Birth': 'Place Of Birth',
      'Main Page': 'Main Page',
      'Religion': 'Religion',
      'Do You Want To Pend Account': 'Do You Want To Pend Account',
      'The Verifying Code is Wrong': 'The Verifying Code is Wrong',
      'Your password is not true , Please cheek your password and try again later':
          'Your password is not true , Please cheek your password and try again later',
      'You have not confirmed your account yet.':
          'You have not confirmed your account yet.',
      'Verified Now': 'Verified Now',
      'Blood Type': 'Blood Type',
      'Location': 'Location',
      'Mobile Number': 'Mobile Number',
      'FamilyState': 'FamilyState',
      'National Id': 'National Id',
      'Special need': 'Special need',
      'Martyr son': 'Martyr son',
      'Student Illness': 'Student Illness',
      'Student Vaccines': 'Student Vaccines',
      '   Student School Info   ': '   Student School Info   ',
      'Username': 'Username',
      'Full Name': 'Full Name',
      'Fee Discount': 'Fee Discount',
      '   Father Info   ': '   Father Info   ',
      'Father Name': 'Father Name',
      'Father Phone': 'Father Phone',
      'Father Work': 'Father Work',
      '   Mother Info   ': '   Mother Info   ',
      'Mother Name': 'Mother Name',
      'Mother Phone': 'Mother Phone',
      'Mother Work': 'Mother Work',
      '   More Info   ': '   More Info   ',
      'Last School Details': 'Last School Details',
      '   File Data   ': '   File Data   ',
      'Add Father Passport': 'Add Father Passport',
      'File Father Passport Dropped!': 'File Father Passport Dropped!',
      'Add Mother Passport': 'Add Mother Passport',
      'File Mother Passport Dropped!': 'File Mother Passport Dropped!',
      'Add Son Passport': 'Add Son Passport',
      'File Son Passport Dropped!': 'File Son Passport Dropped!',
      'Add ID File': 'Add ID File',
      'File Id Dropped!': 'File Id Dropped!',
      'Add Certificate': 'Add Certificate',
      'File Certificate Dropped!': 'File Certificate Dropped!',
      'Add Academic sequence': 'Add Academic sequence',
      'File Academic sequence Dropped!': 'File Academic sequence Dropped!',
      'Add Family notebook': 'Add Family notebook',
      'File Family notebook Dropped!': 'File Family notebook Dropped!',
      'Local ID': 'Local ID',
      'Male': 'Male',
      'Female': 'Female',
      'Muslim': 'Muslim',
      'Christian': 'Christian',
      'Widow': 'Widow',
      'Single': 'Single',
      'Married': 'Married',
      'Divorced': 'Divorced',
      'Click To Add Father Passport\nOr\nDrag And Drop File Here':
          'Click To Add Father Passport\nOr\nDrag And Drop File Here',
      'Done Selected File': 'Done Selected File',
      'Click To Add Mother Passport\nOr\nDrag And Drop File Here':
          'Click To Add Mother Passport\nOr\nDrag And Drop File Here',
      'Click To Add Son Passport\nOr\nDrag And Drop File Here':
          'Click To Add Son Passport\nOr\nDrag And Drop File Here',
      'Click To Add Id\nOr\nDrag And Drop File Here':
          'Click To Add Id\nOr\nDrag And Drop File Here',
      'Click To Add Certificate\nOr\nDrag And Drop File Here':
          'Click To Add Certificate\nOr\nDrag And Drop File Here',
      'Click To Add Academic sequence\nOr\nDrag And Drop File Here':
          'Click To Add Academic sequence\nOr\nDrag And Drop File Here',
      'Click To Add Family notebook\nOr\nDrag And Drop File Here':
          'Click To Add Family notebook\nOr\nDrag And Drop File Here',
      'Syria': 'Syria',
      'Done': 'Done',
      'Student illeness': 'Student illeness',
      'Student Vaccine': 'Student Vaccine',
      'Add Picture': 'Add Picture',

////////////////////////////////section 1 and home appbar////////////////////////////////////
      'WE CARE ABOUT \n YOUR FUTURE': 'WE CARE ABOUT \n YOUR FUTURE',
      'Join us to enter a better world filled with advanced educational methods through Virtual Modern School':
          'Join us to enter a better world filled with advanced educational methods through Virtual Modern School',
      'Enroll': 'Enroll',
      'WE CARE ABOUT YOUR FUTURE': 'WE CARE ABOUT YOUR FUTURE',
      'Sign In': 'Sign In',
      'Teachers': 'Teachers',
      'Students': 'Students',
      'Visitors': 'Visitors',
/////////////////////////section 2////////////////////////////////////////////
      'People with special needs who are residing in Syria are uncapable to study in regular schools uncapable':
          'People with special needs who are residing in Syria are uncapable to study in regular schools uncapable',
      'to study uncapable to study in regular schools and exceptional students cases determined by the':
          'to study uncapable to study in regular schools and exceptional students cases determined by the',
      'Ministry of Education at Syrian Arab Diploma granted by the Ministry of Education at Syrian Arab':
          'Ministry of Education at Syrian Arab Diploma granted by the Ministry of Education at Syrian Arab',
      'Republic': 'Republic',
      //////////////////////////////section 3/////////////////////////////
      'How I Can Enroll At Virtual Modern School':
          'How I Can Enroll At Virtual Modern School',
      'Parents of our students can register their children in the Virtual Modern School':
          'Parents of our students can register their sons in the Virtual Modern School',
      'by the following steps:': 'by the following steps:',
      '1. Enter the first and last name of the guardian':
          '1. Enter the first and last name of the guardian',
      '2. Enter the mobile phone number of guardian':
          '2. Enter the mobile phone number of guardian',
      '3. Enter the Syrian national number of the guardian':
          '3. Enter the Syrian national number of the guardian',
      'Read More': 'Read More',
      //////////////////////////////////section 4/////////////////////////////////////
      'Why Us?': 'Why Us?',
      'Virtual Modern School is an online learning platform that helps students to learn the':
          'Virtual Modern School is an online learning platform that helps students to learn the',
      'Syrian Education Curriculum from home. The courses of this platform are designed':
          'Syrian Education Curriculum from home. The courses of this platform are designed',
      'for elementary school, middle school, and high school all in one place.':
          '.for elementary school, middle school, and high school all in one place',
      'Improving educational': 'Improving educational',
      'Skills': 'Skills',
      'Smart virtual': 'Smart virtual',
      'meeting': 'meeting',
      'Outstanding': 'Outstanding',
      'user - friendliness': 'user - friendliness',
      'Instant live': 'Instant live',
      'Lessons': 'Lessons',
      'Focus on results': 'Focus on results',
      'Multiple registration': 'Multiple registration',
      'options': 'options',
      ////////////////////////////// section 5/////////////////////////////////////
      'Who Are We': 'Who Are We',
      'is a community of learners, including students, parents, and staff, dedicated to creating a rigorous and':
          'is a community of learners, including students, parents, and staff, dedicated to creating a rigorous and',
      'VIRTUAL MODERN SCHOOL (VMS)': 'VIRTUAL MODERN SCHOOL (VMS)',
      'inclusive educational environment. VMS students are goal-oriented, critical thinkers, and community leaders':
          'inclusive educational environment. VMS students are goal-oriented, critical thinkers, and community leaders',
      'committed to achieving high levels of integrity and academic success.':
          '.committed to achieving high levels of integrity and academic success',
      'VIRTUAL MODERN SCHOOL (VMS) staff aim to create a supportive':
          'VIRTUAL MODERN SCHOOL (VMS) staff aim to create a supportive',
      'and challenging environment for all students to reach their potential,':
          'and challenging environment for all students to reach their potential,',
      'engaging in continuous improvement through goal setting and':
          'engaging in continuous improvement through goal setting and',
      'reflection': '.reflection',
      'Virtual Modern School': 'Virtual Modern School',

      /////////////////////section 6///////////////////////////

      'What Do We Do': 'What Do We Do',
      'We develop a culture of excellence that includes a robust instructional program aligned to the':
          'We develop a culture of excellence that includes a robust instructional program aligned to the',
      'highest standards with a focus on implementing balanced literacy through reading and writing':
          'highest standards with a focus on implementing balanced literacy through reading and writing',
      'workshops, while cultivating competency across all subject areas.':
          '.workshops, while cultivating competency across all subject areas',
      'We are committed to developing well-rounded students who embody our core values: Be Safe, Be Respectful, Be Responsible, and Be Mindful. Our vibrant learning environment encourages discovery and creative expression, making every student feel valued.\n\nWe provide our educators with robust professional development to enhance teaching practices and boost student success. Through collaboration and a community schools model, we align resources to ensure every student thrives. Join us in our journey towards excellence!':
          'We are committed to developing well-rounded students who embody our core values: Be Safe, Be Respectful, Be Responsible, and Be Mindful. Our vibrant learning environment encourages discovery and creative expression, making every student feel valued \n\nWe provide our educators with robust professional development to enhance teaching practices and boost student success. Through collaboration and a community schools model, we align resources to ensure every student thrives. Join us in our journey towards excellence',

      //////////////////////////section 7////////////////////////////
      'Openning Hours': 'Openning Hours',
      '8 AM -----> 1 PM': 'from 8 AM at 1 PM',
      '3 PM -----> 8 PM': 'from 3 PM at 8 PM',
      'Contact Details': 'Contact Details',
      'Shakib Arslan Street - Engineers Syndicate Building - 2nd Floor - AlSuwaidaa - Syria':
          'Shakib Arslan Street - Engineers Syndicate Building - 2nd Floor - AlSuwaidaa - Syria',
      'All Rights reserved. Copyright': 'All Rights reserved. Copyright',
      //////////////////////////////////////////////
      'Login': 'Login',
      'Update Student': 'Update Student',
      'Pend Student': 'Pend Student',
      'Do You Want To Pend ': 'Do You Want To Pend ',
      'Student?': 'Student?',
      'Yes': 'Yes',
      'Files': 'Files',
      'Links': 'Links',
      'Pages': 'Pages',
      'Quiz': 'Quiz',
      'Resend!': 'Resend!',
      'Verify': 'Verify',
      'Question Bank': 'Question Bank',
      'Trivia': 'Trivia',
      'Enter Verification Code Sent to:': 'Enter Verification Code Sent to:',
      'No Penalties': 'No Penalties',
      'No Content': 'No Content',
      'UnPend Student': 'UnPend Student',
      'Do You Want To UnPend': 'Do You Want To UnPend',
      'UnPend This Student': 'UnPend This Student',
      'Realagon': 'Religion',
      'Family State': 'Family State',
      'Last School Detail': 'Last School Detail',
      'Edit Student': 'Edit Student',
      'Edite': 'Edit',
      'Error Code': 'Error Code',
      'Username not found': 'Username not found',
      'Info': 'Info',
      'Show only selected items': 'Show only selected items',
      'Do You Want To Deletee': 'Do You Want To Delete',
      'No Result': 'No Result',
      'Guardian Name': 'Guardian Name',
      'Guardian National ID': 'Guardian National ID',
      'Guardian Email': 'Guardian Email',
      'Guardian Phone Number': 'Guardian Phone Number',
      'Edit Guardian': 'Edit Guardian',
      'Confirm Password': 'Confirm Password',
      'Add Guardian': 'Add Guardian',
      'Email': 'Email',
      'First Lesson': 'First Lesson',
      'second Lesson': 'second Lesson',
      'Third Lesson': 'Third Lesson',
      'Forth Lesson': 'Forth Lesson',
      'Fifth Lesson': 'Fifth Lesson',
      'Sixth Lesson': 'Sixth Lesson',
      'Seventh Lesson': 'Seventh Lesson',
      'Guardian Username': 'Guardian Username',
      'Name': 'Name',
      'phone Number': 'phone Number',
      'National ID': 'National ID',
      'Set All As a Holiday': 'Set All As a Holiday',
      'Cause': 'Cause',
      'No Subjects': 'No Subjects',
      'No Grade': 'No Grade',
      'No Sessions': 'No Sessions',
      'Enroll Now': 'Enroll Now',
      'You Have Account ?': 'You Have Account ?',
      'Enter The Reason For Absence': 'Enter The Reason For Absence',
      'The reason for the absence of the all students':
          'The reason for the absence of the all student',
      'Present': 'Present',
      'Truant': 'Truant',
      'No Teachers': 'No Teachers',
      'Late': 'Late',
      'There is no open academic year available to add classes to. Please add an open academic year and try again.':
          'There is no open academic year available to add classes to. Please add an open academic year and try again.',
      'Holiday': 'Holiday',
      'The reason for the absence of the student':
          'The reason for the absence of the student',
      'Attendance Today Has Been Uploaded':
          'Attendance Today Has Been Uploaded',
      'Attendence': 'Attendence',
      'Subject': 'Subject',
      'Add Teacher': 'Add Teacher',
      'Contract Type': 'Contract Type',
      'Full Time': 'Full Time',
      'hours': 'hours',
      'Student Marks': 'Student Marks',
      'Hours': 'Hours',
      'Morning Time': 'Morning Time',
      'Evening Time': 'Evening Time',
      'This Teacher Does Not Contain Any Data':
          'This Teacher Does Not Contain Any Data',
      'Mobile: ': 'Mobile: ',
      'Whatsapp Number': 'Whatsapp Number',
      'Teacherr': 'Teacherr',
      'Do You Want To Deletet': 'Do You Want To Delete',
      'Delete Teacher': 'Delete Teacher',
      'If You Deselected The Illness The File Will Remove':
          'If You Deselected The Illness The File Will Remove',
      'If You Click Yes The File Will Remove':
          'If You Click Yes The File Will Remove',
      'illness File': 'illness File',
      'Vaccine File': 'Vaccine File',
      'Employee Illness': 'Employee Illness',
      'Teacher Illness': 'Teacher Illness',
      'The reason for the absence of the all Teachers':
          'The reason for the absence of the all Teachers',
      'Vacation': 'Vacation',
      'Find Your Account': 'Find Your Account',
      "att": "",
      "sub": "",
      "Year": "Year",
      "You Don`t Have Account ?": "You Don`t Have Account ?",
      'Subjects': 'Subjects',
      'Subjectssss': 'Subjects',
      'My Account': 'My Account',

      'Job Title': 'Job Title',
      "Manager": "Manager",
      "Dustman": "Dustman",
      "Guard": "Guard",
      "My Attendance": "My Attendance",
      "Show Approve Files": "Show Approve Files",
      "Registration": "Registration",
      "Secretariat": "Secretariat",
      "Secretary": "Secretary",
      "Supervisor": "Supervisor",
      "Accountant": "Accountant",
      "Technical Support": "Technical Support",
      "Media": "Media",
      "Studentsss": "Students",
      "Technical Support Manager": "Technical Support Manager",
      'Add Employee': 'Add Employee',
      'Roll': 'Role',
      'Add Full Employee': 'Add Full Employee',
      'Observer': 'Observer',
      'Admin': "Admin",
      'My Children': "My Children",
      'Not Selected': "Not Selected",
      'Sub Admin': "Sub Admin",
      'Salary': 'Salary',
      'Employee': 'Employees',
      'Employee Bank Info': 'Employee Bank Info',
      'IFSC Code': 'IFSC Code',

      'This Employee Does Not Contain Any Data':
          'This Employee Does Not Contain Any Data',
      'Employeey': 'Employee',
      'Do You Want To Deletey': 'Do You Want To Delete',
      'Delete Employee': 'Delete Employee',
      'No Employees': 'No Employees',

      'Edit Employee': 'Edit Employee',
      'The reason for the absence of the all employee':
          'The reason for the absence of the all employee',

      'The reason for the absence of the employee':
          'The reason for the absence of the employee',

      'Add Virtual User': 'Add Virtual User',
      'No Virtual User': 'No Virtual User',
      'Do You Want To Deletec': 'Do You Want To Delete',
      'Virtual User': 'Virtual User',
      'observer': 'observer',
      'class': 'class',

      'Class En - Name': 'Class En - Name',
      'Class Ar - Name': 'Class Ar - Name',
      'Admin Account': 'Admin Account',
      'No selected curriculum': 'No selected curriculum',
      'Drive URL': 'Drive URL',
      'Add Class': 'Add Class',
      'Grade En - Name': 'Grade En - Name',
      'Grade Ar - Name': 'Grade Ar - Name',
      'Curriculums': 'Curriculums',
      'Edit Class': 'Edit Class',
      'Do You Want To Deleteclass': 'Do You Want To Delete',
      'Classs': 'Class',
      'Delete Class': 'Delete Class',
      'No Classes': 'No Classes',

      'Curriculum English Name': 'Curriculum English Name',
      'Failed subject': 'Failed Curriculum',
      'Is Failed subject': 'Is Curriculum Failing',
      'Add Curriculum': 'Add Curriculum',
      'Please select true value': 'Please select true value',
      'Click To Add File\nOr\nDrag And Drop File Here':
          'Click To Add File\nOr\nDrag And Drop File Here',
      'Click To Add Image\nOr\nDrag And Drop Image Here':
          'Click To Add Image\nOr\nDrag And Drop Image Here',
      'Done Selected Image': 'Done Selected Image',
      "The First Semester": "The First Semester",
      "The Second Semester": "The Second Semester",
      "The Third Semester": "The Third Semester",
      'Max Mark :': 'Max Mark :',
      'Passing Mark :': 'Passing Mark :',
      'Is Failure Agent :': 'Is Failure Curriculum :',
      'Do You Want To Deletecur': 'Do You Want To Delete',
      'Curriculumm': 'Curriculum',
      'Delete Curriculum': 'Delete Curriculum',
      'No Curriculum': 'No Curriculum',

      'PDF File Successfully Dropped!': 'PDF File Successfully Dropped!',
      'Error: Unsupported File Type.': 'Error: Unsupported File Type.',
      'Error: Only One File Is Allowed.': 'Error: Only One File Is Allowed.',
      'Add Book': 'Add Book',
      'Add Electronic Book': 'Add Electronic Book',
      'English Name': 'English Name',
      'Do You Want To Deletebook': 'Do You Want To Delete',
      'Book': 'Book',
      'Delete Electronic Book': 'Delete Electronic Book',
      'No Electronic Book': 'No Electronic Books',

      'Fee Count': 'Fee Count',
      'Add Grade': 'Add Grade',
      'Grade Name': 'Grade Name',
      'Do You Want To Deletegarde': 'Do You Want To Delete',
      'Gradee': 'Grade',
      'Delete Grade': 'Delete Grade',
      'Edit Grade': 'Edit Grade',
      'Is chronic : Yes': 'Is chronic : Yes',
      'Is chronic : No': 'Is chronic : No',
      'Illnesss': 'Illness',
      'Do You Want To Deleteill': 'Do You Want To Delete',
      'Delete Illness': 'Delete Illness',
      'No Illness': 'No Illness',
      'Is Chronic': 'Is Chronic',
      'Add Illness': 'Add Illness',
      'Division En - Name': 'Division En - Name',
      'Division Ar - Name': 'Division Ar - Name',
      'Meet URL': 'Meet URL',
      'Add Division': 'Add Division',
      'Edit Division': 'Edit Division',
      'Do You Want To Deletediv': 'Do You Want To Deletediv',
      'Divisionn': 'Division',
      'Delete Division': 'Delete Division',
      'No Divisions': 'No Divisions',
      'School Name': 'School Name',
      'License Number': 'License Number',
      'Village': 'Village',
      'Region': 'Region',
      'Phone': 'Phone',
      'Work Begin Year': 'Work Begin Year',
      'Creation Year': 'Creation Year',
      'Fax': 'Fax',
      "Country": "Country",
      'Not yet evaluated': 'Not yet evaluated',
      'Clinic Name': 'Clinic Name',
      'Congregation number': 'Congregation Number',
      'Previous name': 'Previous Name',
      'Town Chip': 'TownShip',
      'Outstanding School': 'Outstanding School',
      'Taken Over School': 'Taken Over School',
      'Reassignment Teachers': 'Reassignment Teachers',
      'Martyrs Sons': 'Martyrs Sons',
      'Internet Connection': 'Internet Connection',
      'Government Connection': 'Government Connection',
      'Joint Building': 'Joint Building',
      'Industrial Section': 'Industrial Section',
      'Study Year': 'Study Year',
      'Enter Year': 'Enter Year',
      'Add Session': 'Add Session',
      'Yes Close': 'Yes Close',
      'Closed': 'Closed',
      'Close Session': 'Close Session',
      'Close': 'Close',
      'Start Date :': 'Start Date :',
      'End Date :': 'End Date :',
      'Do You Want To Deletess': 'Do You Want To Delete',
      'Sessionn': 'Session',
      'Delete Session': 'Delete Session',
      'Edit Session': 'Edit Session',
      'Opened': 'Opened',
      'Subject En - Name': 'Subject En - Name',
      'Subject Ar - Name': 'Subject Ar - Name',
      'Add Subject': 'Add Subject',
      'Subject Name': 'Subject Name',
      'Do You Want To Deletesub': 'Do You Want To Delete',
      'Subjectt': 'Subjectt',
      'Delete Subject': 'Delete Subject',
      'Edit Subject': 'Edit Subject',
      'Role': 'Role',
      'Action': 'Action',
      'SubAdmin': 'SubAdmin',
      'Guardian': 'Guardian',
      'Up 200': 'Up 200',
      'Device Info': 'Device Info',
      'Add Vaccine': 'Add Vaccine',
      'Location :': 'Location :',
      'Vaccinee': 'Vaccine',
      'AM': 'AM',
      'PM': 'PM',
      'Arabic Address': 'Arabic Address',
      'English Address': 'English Address',
      'English Village': 'English Village',
      'Arabic Village': 'Arabic Village',
      'Do You Want To Deletevac': 'Do You Want To Delete',
      'Delete Vaccine': 'Delete Vaccine',
      'No Vaccine': 'No Vaccine',
      'No Data in Exam Table': 'No Data in Exam Table',
      'Tools': 'Tools',
      'Add Text': 'Add Text',
      'Export As Pdf': 'Export As Pdf',
      'Edit text': 'Edit text',
      'Enter text': 'Enter text',
      'Font Size: ': 'Font Size: ',
      'Add Marks For All': 'Add Marks For All',
      'Students Marks': 'Students Marks',
      'Selected Class': 'Selected Class',
      'Selected Division': 'Selected Division',
      'Selected Curriculum': 'Selected Curriculum',
      'No Quiz Type': 'No Quiz Type',

      'Group Name': 'Group Name',
      'ratio': 'ratio',
      'Group Items': 'Group Items',
      'Item ratio': 'Item ratio',
      'Item Name': 'Item Name',
      'Add Group': 'Add Group',
      'Add a New Group': 'Add a New Group',
      'Is Quizable': 'Is Quizable',
      'Add Item': 'Add Item',
      'Add Group Item': 'Add Group Item',
      'Edit Item': 'Edit Item',
      'Edit Group Item': 'Edit Group Item',
      'Rerange': 'Rearrange',
      'Rerange Group': 'Rearrange Group',
      'Confirm Delete': 'Confirm Delete',
      'Are you sure you want to delete this group?':
          'Are you sure you want to delete this group?',
      'Edit Group': 'Edit Group',
      'Editgroup': 'Edit',
      'Groupp': 'Group',
      'Please Select Class First': 'Please Select Class First',
      'Select Type': 'Select Type',
      'Type Operations': 'Type Operations',
      'No types available': 'No types available',
      'Selected:': 'Selected:',
      'Sum': 'Sum',
      'Average': 'Average',
      'Edit Teacher': 'Edit Teacher',
      'Teacher Bank Info': 'Teacher Bank Info',
      'FullTime': 'Full Time',
      'Curriculum English Name - English Class Name':
          'Curriculum English Name -English Class Name',
      'Curriculum Name - Class Name': 'Curriculum Name - Class Name',
      'Curriculum List': 'Curriculum List',
      'Content En Name': 'Content En Name',
      'Content Name': 'Content Name',
      'Add Content': 'Add Content',
      'Edit Content': 'Edit Content',
      'This Subjact has Curriculums': 'This Subjact has Curriculums',
      'You Can`t Delete This Subject': 'You Can`t Delete This Subject',
      'Ratio': 'Ratio',
      'StudyShare Table': 'StudyShare Table',
      'Attendences': 'Attendence',
      'StudyShare table': 'StudyShare table',
      'Father Passport': 'Father Passport',
      'Mother Passport': 'Mother Passport',
      'Son Passport': 'Son Passport',
      'ID File': 'ID File',
      'Certificate': 'Certificate',
      'Academic sequence': 'Academic sequence',
      'Family notebook': 'Family notebook',
      'Degree': 'Degree',
      'Students Marks in': 'Students Marks in Curriculum',
      'State': 'State',
      'Guardian Mobile': 'Guardian Mobile',
      'Student Name': 'Student Name',
      'Student Class': 'Student Class',
      'Request Date': 'Request Date',
      'IP Address': 'IP Address',
      'Platform': 'Platform',
      'No Time yet': 'No Time yet',
      'No Address yet': 'No Address yet',
      'Browser Version': 'Browser Version',
      'Device Type': 'Device Type',
      'Device': 'Device',
      'Detail': 'Detail',
      'admin': 'admin',
      'teacher': 'teacher',
      'guardian': 'guardian',
      'Classes': 'Classes',
      'Divisions': 'Divisions',
      'Quiz Types': 'Quiz Types',
      'Report Card Settings': 'Report Card Settings',
      'student': 'student',
      'Vaccine': 'Vaccines',
      'illness': 'Illness',
      'UnPend This Account': 'UnPend This Account',
      'UnPend Account': 'UnPend Account',
      'Do You Want To UnPend Account': 'Do You Want To UnPend Account',
      'Pend Account': 'Pend Account',
      'Youtube URL': 'Youtube URL',

      'Start Time (Evening)': 'Evening Start Time',
      'End Time (Evening)': 'Evening End Time',
      'Start Time (Morning)': 'Morning Start Time',
      'End Time (Morning)': 'Morning End Time',

      'As-Suwayda': 'As-Suwayda',
      'Public Register Number': 'Public Register Number',
      'Add Rewards': 'Add Reward',
      'Do You Want To DeleteeAtt': 'Do You Want To Delete',
      'Attendenceatt': 'Attendence',
      'Delete Attendence': 'Delete Attendence',
      'My_Illness': 'My Illness',
      'My Illness': 'My Illness',
      'My_Curr': 'My Curriculum',
      'My curr': 'My Curriculum',
      'You have has data in your account yet.':
          'You have has data in your account yet.',
      'Add Data Now': 'Add Data Now',
      'you can not close this session': 'you can not close this session',
      'Re-order': 'Re-order',
      'Import': 'Import',
      'Marks': 'Marks',
      'Show Files': 'Show Files',
      'Select Session': 'Select Session',
      'Move From Session': 'Import From Session',
      'LMS Platform': 'LMS Platform',
      'Homework': 'Homework',
      'File Homework': 'File Homework',
      'Questions Homework': 'Questions Homework',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
    }
  };
}
