class Languages {
  static Map<String, Map<String, String>> translations = {
    'ar': {
      'Welcome Laith Haitham Azzam': 'مرحبا',
      'Have A Nice Day At Work': 'أتمنى لك يوم جيد في العمل',
      'Illness and Vaccines': 'الأمراض و اللقحات',
      'Illness': 'الأمراض',
      'No Attendance': 'لا يوجد حظور بعد',
      'Vaccines': 'اللقحات',
      'Rewards and Penalties': 'المكافئات و العقوبات',
      'Rewards': 'المكافئات',
      'No Rewards': 'لا يوجد مكافئات',
      'No Penalty': 'لا يوجد عقوبات',
      'Penalties': 'العقوبات',
      'Attendance Today': 'حضور اليوم',
      'Employees\nAttendance': 'حضور الموظفين',
      'Students\nAttendance': 'حضور الطلاب',
      'Teachers\nAttendance': 'حضور المعلمين',
      'Percentage\nStudents': 'نسبة الطلاب',
      'Percentage\nTeacher': 'نسبة المعلمين',
      'Percentage\nEmployee': 'نسبة الموظفين',
      'Total Students': 'إجمالي الطلاب',
      'Total Teacher': 'إجمالي المعلمين',
      'Total Employee': 'إجمالي الموظفين',
      'Total Visitor': 'إجمالي الزائرين',
      'Total Books': 'إجمالي الكتب',
      'Total Division': 'إجمالي الشُعب',
      'Dashboard': 'الإحصائيات',
      'Enroll Requests': 'طلبات التسجيل',
      'Exam Table': "جدول الامتحان",
      'School Time Table': 'جدول الدوام',
      'All Students': 'كل الطلاب',
      'Study Year Students': 'طلاب العام الدراسي',
      'All Guardians': 'أولياء الأمور',
      'Student Attendance': 'حضور الطلاب',
      'Students Attendance Managment': 'إدارة حضور الطلاب',
      'Teacher Management': 'إدارة المعلمين',
      'Teacher Status': 'حضور المعلمين',
      'Teacher Attendance Managment': 'إدارة حضور المعلمين',
      'Employee Management': 'إدارة الموظفين',
      'Employee Attendance': 'حضور الموظفين',
      'Employee Attendance Manage': 'إدارة حضور الموظفين',
      'Virtual User Management': 'إدارة الموظفين الافتراضيين',
      'Session Management': 'إدارة السنوات',
      'Grade Management': 'إدارة المراحل الدراسية',
      'Subject Management': 'إدارة المواد',
      'Class Management': 'إدارة الصفوف',
      'Division Management': 'إدارة الشعب',
      'Curriculum Management': 'إدارة المناهج',
      'School Data Management': 'إدارة معلومات المدرسة',
      'Electronic Library': 'المكتبة الإلكترونية',
      'Transaction': 'سجل المناقلات',
      'Illness Screen': 'الأمراض',
      'Vaccine Screen': 'اللقاحات',
      'Presence of students': 'نسب الطلاب',
      'Presence this session students': 'نسب طلاب هذا العام',
      'Total this year': 'إجمالي هذه السنة',
      'Add': 'إضافة',
      'Penalty En - Name': 'الاسم الإنكليزي للعقوبة',
      'Penalty Ar - Name': 'الاسم العربي للعقوبة',
      'Details': 'تفاصيل',
      'Add Penalty': 'إضافة عقوبة',
      'Delete': 'حذف',
      'Cancel': 'إلغاء',
      'Do You Want To Delete': 'هل تريد حذف العقوبة',
      'penalty': '',
      'Edit': 'تعديل',
      'Quiz Type': 'انواع الاختبارات',
      'Operation': 'العمليات',
      'Penalty Name': 'اسم العقوبة',
      'Delete Penalty': 'حذف العقوبة',
      'Edit Penalty': 'تعديل العقوبة',
      'Status': 'الحالة',
      'No Requests': 'لا يوجد طلبات',
      'Guardian Info :': 'معلومات ولي الأمر:',
      'Name :': 'الاسم:',
      'Mobile:': 'الهاتف:',
      'Email: ': 'البريد الإلكتروني: ',
      'National ID:': 'الرقم الوطني:',
      'Student Info:': 'معلومات الطالب:',
      'Current Class:': 'الصف الحالي:',
      'Previous Class:': 'الصف السابق',
      'Manage': 'إدارة',
      'Reject': 'رفض',
      'Approve': 'موافقة',
      'Rejected': 'مرفوض',
      'Pending': 'معلق',
      'Partially': 'جزئياً',
      'Search By Name': 'البحث حسب الاسم',
      'Class': 'الصف',
      'Division': 'شعبة',
      'Manage Student': 'إدارة الطالب',
      'Add Exam': 'إضافة امتحان',
      'Date': 'التاريح',
      'Type': 'النوع',
      'Curriculum Name': 'اسم المنهاج',
      'Period': 'الفترة الزمنية',
      'Max Mark': 'العلامة العظمى',
      'Passing Mark': 'الحد الأدنى للنجاح',
      'Operations': 'العمليات',
      'Edit Exam': 'تعديل الامتحان',
      'Semester': 'الفصل',
      'Curriculum': 'المنهاج',
      'season': 'الفصل',
      'New Text': 'نص جديد',
      'Min Mark': 'الحد الأدنى للنجاح',
      'Time': 'الوقت',
      'Morning': 'صباحي',
      'Evening': 'مسائي',

      'Search': 'البحث',
      'Settings': 'الاعدادات',
      'Profile': 'صفحتي',
      'Personal': 'شخصي',
      'Password': 'كلمة السر',
      'Account And Password': 'الحساب و كلمة السر',
      'Appearance': 'المظهر و اللغة',
      'Light Theme': 'النمط الفاتح',
      'Dark Theme': 'النمط الداكن',
      'Language': 'اللغة',
      'English': 'English',
      'Arabic': 'العربية',
      'My Email': 'بريدي الالكتروني',
      'Edit Picture': 'تعديل الصورة',
      'Delete Picture': 'حذف الصورة',
      'Logout': 'تسجيل الخروج',
      'Bank Info': 'معلومات الحساب و الدفع',
      'Personal Information': 'معلوماتي العامة',
      'Application and Profile Settings': 'اعدادات التطبيق و الملف الشخصي',
      'Application Theem': 'نمط التطبيق',
      'Social Media Info': 'معلومات التواصل الاجتماعي',
      'Your Password': 'كلمتي السرية',
      'Old Password': 'كلمة السر القديمة',
      'Your Verification Code': 'رمز التحقق',
      'Change Password': 'تغيير كلمة السر',
      'New Password': 'كلمة السر الجديدة',
      'Confirm New Password': 'تأكيد كلمة السر الجديدة',
      'More Information': 'معلومات اضافية',
      'Technical Support': 'دعم تقني',
      'First Name': 'الاسم الأول',
      'Last Name': 'الاسم الأخير',
      'Phone Number': 'رقم الهاتف',
      'Emergency Number': 'رقم هاتف للطوارئ',
      'Join Date': 'تاريخ الانضمام',
      'Birthdate': 'تاريخ الميلاد',
      'Address': 'العنوان',
      'Current Address': 'العنوان الحالي',
      'Gender': 'الجنس',
      'Family Status': 'الحالة الأُسرية',
      'Career History': 'المسيرة المهنية',
      'Qualification': 'المؤهلات',
      'Experience': 'الخبرات',
      'Note': 'ملاحظات',
      'Facebook URL': 'رابط حسابك الفيسبوك ',
      'Instagram URL': 'رابط حسابك الانستغرام ',
      'X Platform URL': 'X رابط حسابك منصة',
      'Linkedin URL': 'رابط حسابك اللينكد إن ',
      'Bank Name': 'اسم البنك',
      'Bank Account Title': 'اسم الحساب البنكي',
      'Bank Branch Name': 'اسم الفرع البنكي',
      'Bank Account Number': 'رقم الحساب البنكي',
      'Save': 'حفظ',
      '': '',
      'Select Class First': 'اختر الصف أولاً',
      'Select Division First': 'اختر الشعبة أولاً',
      'Day': 'اليوم',
      'Teacher': 'المعلم',
      'Operation of Lessons': 'العلميات على الحصص الدراسية',
      'Sunday': 'الأحد',
      'Monday': 'الإثنين',
      'Tuesday': 'الثلاثاء',
      'Wednesday': 'الأربعاء',
      'Thursday': 'الخميس',
      'First\n Lesson': 'الحصة \n الأولى',
      'second\n Lesson': 'الحصة \n الثانية',
      'Third\n Lesson': 'الحصة \n الثالثة',
      'Forth\n Lesson': 'الحصة \n الرابعة',
      'Fifth\n Lesson': 'الحصة \n الخامسة',
      'Sixth\n Lesson': 'الحصة \n السادسة',
      'Seventh\n Lesson': 'الحصة \n السابعة',
      'Session': 'العام الدراسي',
      'Grade': 'المرحلة الدراسية',
      'Email:': 'البريد الألكتروني:',
      'Grade Level:': 'المرحلة الدراسية:',
      'Delete Students': 'حذف الطالب',
      'Student': '',
      'No Students': 'لا يوجد طلاب',
      'Reward': 'المكافآت',
      'Penalty': 'العقوبات',
      'Start Date': 'تاريخ البداية',
      'End Date': 'تاريخ النهاية',
      'Reason': 'السبب',
      'Penalties And Rewards': 'المكافآت و العقوبات',
      'Passing': 'ناجح',
      'Failed': 'راسب',
      'Export Certificate': 'تصدير الجلاء',
      'Send': 'إرسال',
      'Logout from Current Session': 'تسجيل الخروج من الجلسة الحالية',
      'Logout from All Sessions': 'تسجيل الخروج من كافة الجلسات',
      'Penaltyy': 'عقوبة',
      'The Reason': 'السبب',
      'Punishing Student': 'معاقبة الطالب',
      'Punishing': 'معاقبة',
      'Contact Us': 'التواصل معنا',
      'Next': 'التالي',

      'AboutUs': 'حول',
      'WhyUs': 'لماذا نحن',
      'Programs': 'البرمامج',
      'Enrollment': 'التسجيل',
      'Eligibility': 'المؤهلون',

      'Back': 'رجوع',
      'Add Students': 'إضافة طالب',
      'Mobile Number :': 'رقم الهاتف:',
      'Select Garduans To Add Students': 'اختر ولي الأمر لإضافة طلاب',
      'Place Of Birth': 'مكان الولادة',
      'Religion': 'الدين',
      'Blood Type': 'زمرة الدم',
      'Location': 'الموقع',
      'Mobile Number': 'رقم الهاتف',
      'FamilyState': 'الحالة الأسرية',
      'National Id': 'الرقم الوطني',
      'Special need': 'ذوي احتياجات خاصة',
      'Martyr son': 'ابن شهيد',
      'Student Illness': 'أمراض الطالب',
      'Student Vaccines': 'لقاحات الطالب',
      '   Student School Info   ': '   معلومات الطالب المدرسية   ',
      'Username': 'اسم المستخدم',
      'Fee Discount': 'نسبة الخصم',
      '   Father Info   ': '   معلومات الأب   ',
      'Father Name': 'اسم الأب',
      'Father Phone': 'رقم هاتف الأب',
      'Father Work': 'عمل الأب',
      '   Mother Info   ': '   معلومات الأم   ',
      'Mother Name': 'اسم الأم',
      'Mother Phone': 'رقم هاتف الأم',
      'Mother Work': 'عمل الأم',
      '   More Info   ': '   معلومات أخرى   ',
      'Last School Details': 'تفاصيل المدرسة السابقة',
      '   File Data   ': '   بيانات الملفات   ',
      'Add Father Passport': 'إضافة جواز سفر الأب',
      'File Father Passport Dropped!': 'جواز سفر الأب تم لصقه',
      'Add Mother Passport': 'إضافة جواز سفر الأم',
      'File Mother Passport Dropped!': 'جواز سفر الأم تم لصقه',
      'Add Son Passport': 'إضافة جواز سفر الابن',
      'File Son Passport Dropped!': 'جواز سفر الابن تم لصقه',
      'Add ID File': 'إضافة ملف التعريف الشخصي',
      'File Id Dropped!': 'ملف التعريف تم لصقه',
      'Add Certificate': 'إضافة شهادة',
      'File Certificate Dropped!': 'الشهادة تم لصقها',
      'Add Academic sequence': 'إضافة تسلسل أكاديمي',
      'File Academic sequence Dropped!': 'التسلسل الأكديمي تم لصقه',
      'Add Family notebook': 'إضافة دفتر العائلة',
      'File Family notebook Dropped!': 'دفتر العائلة تم لصقه',
      "Local ID": "رقم التعريف الشخصي المحلي",
      'Male': 'ذكر',
      'Female': 'أنثى',
      'Muslim': 'مسلم',
      'Christian': 'مسيحي',
      'Widow': 'أرمل',
      'Single': 'أعزب',
      'Syria': 'سوريا',
      'Married': 'متزوج',
      'Divorced': 'مطلق',
      'Click To Add Father Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الأب\nأو\nاسحب وأفلت الملف هنا',
      'Done Selected File': 'تم اختيار الملف',
      'Click To Add Mother Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الأم\nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Son Passport\nOr\nDrag And Drop File Here':
          'اضغط لإضافة جواز سفر الابن\nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Id\nOr\nDrag And Drop File Here':
          'اضغط لإضافة ملف التعريف الشخصي  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Certificate\nOr\nDrag And Drop File Here':
          'اضغط لإضافة شهادة  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Academic sequence\nOr\nDrag And Drop File Here':
          'اضغط لإضافة تسلسل أكديمي  \nأو\nاسحب وأفلت الملف هنا',
      'Click To Add Family notebook\nOr\nDrag And Drop File Here':
          'اضغط لإضافة دفتر العائلة  \nأو\nاسحب وأفلت الملف هنا',
      'Student illeness': 'أمراض الطالب',
      'Done': "تم",
      'Add Picture': "اضافة صورة",
      'Complete the registration details before starting':
          "استكمال بيانات التسجيل قبل البدء",
      'Student Vaccine': "لقاحات الطالب",
      'Add Your Photo Profile': "اضف صورة ملفك الشخصي",

      /////////////////////////////////section 1 and home appbar////////////////////////

      'WE CARE ABOUT \n YOUR FUTURE': 'نحن نعتني\n بمستقبلك',
      'Join us to enter a better world filled with advanced educational methods through Virtual Modern School':
          'انضم إلينا لدخول عالم أفضل مليء بالأساليب التعليمية المتطورة من خلال المدرسة الافتراضية الحديثة',
      'Enroll': 'تسجيل',
      'Sign In': 'تسجيل دخول',
      'Teachers': 'المعلمين',
      'Students': 'الطلاب',
      'Visitors': 'الزائرين',
/////////////////////////////////////section 2///////////////////////////////
      'Who Can We Register At Virtual Modern School':
          'من يمكنهم التسجيل في المدرسة الافتراضية الحديثة',
      'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary':
          'يمكن لأي شخص يقيم خارج سوريا ويرغب في دراسة المناهج التعليمية السورية من المرحلة  ',
      'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted':
          'الابتدائية إلى المرحلة المتوسطة والثانوية التسجيل والتخرج للحصول على شهادة ',
      'by the Ministry of Education at Syrian Arab Republic':
          'الثانوية العامة المقدمة من وزارة التربية في الجمهورية العربية السورية',
      'People with special needs who are residing in Syria are uncapable to study in regular schools uncapable':
          'الأشخاص ذوو الاحتياجات الخاصة المقيمون في سوريا غير قادرين على الدراسة في ',
      'to study uncapable to study in regular schools and exceptional students cases determined by the':
          'المدارس العادية وحالات الطلاب الاستثنائيين التي تحددها وزارة التربية والتعليم',
      'Ministry of Education at Syrian Arab Diploma granted by the Ministry of Education at Syrian Arab':
          'بالدبلوم العربي السوري الممنوح من وزارة التربية في الجمهورية العربية السورية',
      'Republic': '',

      //////////////////////////section 3////////////////////////////
      'How I Can Enroll At Virtual Modern School':
          'كيف يمكنني التسجيل في المدرسة الافتراضية الحديثة',
      'Parents of our students can register their children in the Virtual Modern School':
          'يمكن لأولياء أمور طلابنا تسجيل أبنائهم في المدرسة الحديثة الافتراضية',
      'by the following steps:': 'بالخطوات التالية:',
      '1. Enter the first and last name of the guardian':
          '1. أدخل الاسم الأول والأخير لوَليّ الأمر',
      '2. Enter the mobile phone number of guardian':
          '2. أدخل رقم الهاتف المحمول لوَليّ الأمر ',
      '3. Enter the Syrian national number of the guardian':
          '3. أدخل الرقم القومي السوري لوَليّ الأمر',
      'Read More': 'قراءة المزيد',

      ////////////////////////////////////section 4////////////////////////////////
      'Why Us?': 'لماذا نحن',
      'Virtual Modern School is an online learning platform that helps students to learn the':
          'المدرسة الحديثة الافتراضية هي منصة تعليمية عبر الإنترنت تساعد الطلاب على  ',
      'Syrian Education Curriculum from home. The courses of this platform are designed':
          'تعلم المنهج التعليمي السوري من المنزل. تم تصميم الدورات في هذه المنصة للمدرسة الابتدائية،',
      'for elementary school, middle school, and high school all in one place.':
          'والمدرسة المتوسطة، والمدرسة الثانوية في مكان واحد.',

      'Improving educational': 'تحسين مهارات',
      'Skills': 'التعليم',
      'Smart virtual': 'اجتماع افتراضي',
      'meeting': 'ذكي',
      'Outstanding': 'سهولة التعامل ',
      'user - friendliness': 'مع المستخدم',
      'Instant live': 'دروس مباشرة ',
      'Lessons': 'فورية',
      'Focus on results': 'التركيز على النتائج',
      'Multiple registration': 'خيارات تسجيل',
      'options': 'متعددة',
      ///////////////////////////////////section 5//////////////////////////////////////

      'Who Are We': 'من نحن',
      'is a community of learners, including students, parents, and staff, dedicated to creating a rigorous and':
          'المدرسة الحديثة الافتراضية هي مجتمع من المتعلمين ، بما في ذلك الطلاب وأولياء الأمور والموظفين ، مكرسين لإنشاء بيئة صارمة',
      'VIRTUAL MODERN SCHOOL (VMS)': '',
      'inclusive educational environment. VMS students are goal-oriented, critical thinkers, and community leaders':
          ' و بيئة تعليمية شاملة. طلاب المدرسة هادفون ومفكرين نقديين وقادة مجتمع ملتزمون ',
      'committed to achieving high levels of integrity and academic success.':
          'بتحقيق مستويات عالية من النزاهة والنجاح الأكاديمي.',

      'VIRTUAL MODERN SCHOOL (VMS) staff aim to create a supportive':
          'يهدف موظفو المدرسة الحديثة الافتراضية إلى خلق بيئة داعمة وتحديّة',
      'and challenging environment for all students to reach their potential,':
          'لجميع الطلاب للوصول إلى إمكاناتهم، والانخراط في ',
      'engaging in continuous improvement through goal setting and':
          ' تحسين مستمر من خلال تحديد الأهداف والتأمل',
      'reflection': '',
      'Virtual Modern School': 'المدرسة الافتراضية الحديثة ',

      ////////////////////////section 6//////////////////////////

      'What Do We': 'ماذا نفعل',
      'We develop a culture of excellence that includes a robust instructional program aligned to the':
          'نحن نطور ثقافة التميز التي تشمل برنامجًا تعليميًا قويًا يتوافق مع أعلى المعايير،',
      'highest standards with a focus on implementing balanced literacy through reading and writing':
          'مع التركيز على تطبيق محو الأمية المتوازن من خلال ورش عمل القراءة والكتابة،',
      'workshops, while cultivating competency across all subject areas.':
          'مع تعزيز الكفاءة في جميع المواد الدراسية.',
      'We are committed to developing well-rounded students who embody our core values: Be Safe, Be Respectful, Be Responsible, and Be Mindful. Our vibrant learning environment encourages discovery and creative expression, making every student feel valued.\n\nWe provide our educators with robust professional development to enhance teaching practices and boost student success. Through collaboration and a community schools model, we align resources to ensure every student thrives. Join us in our journey towards excellence!':
          'نحن ملتزمون بتطوير طلاب متوازنين يجسدون قيمنا الأساسية: كن آمناً، وكن محترماً، وكن مسؤولا، وكن واعياً. تشجع بيئة التعلم الحيوية لدينا على الاكتشاف والتعبير الإبداعي، مما يجعل كل طالب يشعر بالتقدير.\n\n نحن نقدم لمعلمينا تطويراً مهنياً قوياً لتعزيز ممارسات التدريس وزيادة نجاح الطلاب. من خلال التعاون ونموذج المدارس المجتمعية، نقوم بتنسيق الموارد لضمان ازدهار كل طالب. انضم إلينا في رحلتنا نحو التميز!',
      //////////////////////////////////section 7////////////////////////////////////////
      'Openning Hours': 'ساعات العمل',
      '8 AM -----> 1 PM': '8 صباحاً---------> 1 ظهراً',
      '3 PM -----> 8 PM': '3 ظهراً--------->8 مساءً',
      'Contact Details': 'معلومات التواصل',
      'Shakib Arslan Street - Engineers Syndicate Building - 2nd Floor - AlSuwaidaa - Syria':
          'سوريا - السويداء -شارع شكيب أرسلان - مجمع المهندسيين - الطابق الثاني',
      'All Rights reserved. Copyright': 'جميع الحقوق محفوظة. حقوق النشر',
      //////////////////////////////

      'Login': 'تسجيل الدخول',

      'Update Student': 'تحديث الطالب',
      'Pend Student': 'قفل الحساب',
      'Do You Want To Pend ': 'هل تريد قفل حساب الطالب',
      'Student?': '',
      'Yes': 'نعم',
      'No': 'لا',
      'UnPend Student': 'إلفاء قفل الحساب',
      'Do You Want To UnPend': 'هل تريد إلفاء قفل الحساب',
      'UnPend This Student': 'إلغاء قفل حساب هذا الطالب',
      'Realagon': 'الدين',
      'Family State': 'الحالة الأسرية',
      'Last School Detail': 'معلومات المدرسة السابقة',
      'Edit Student': 'تعديل الطالب',
      'Edite': 'تعديل معلومات',
      'Info': '',
      'Show only selected items': 'عرض العناصر المختارة فقط',
      'Do You Want To Deletee': 'هل تريد حذف الطالب ',
      'No Result': 'لا يوجد نتيجة',
      'Guardian Name': 'اسم ولي الأمر',
      'Guardian National ID': 'الرقم الوطني لوَليّ الأمر',
      'Guardian Email': ' البريد الإلكتروني لوَليّ الأمر ',
      'Guardian Phone Number': 'رقم هاتف لوَليّ الأمر',
      'Edit Guardian': 'تعديل الوَليّ الأمر',
      'Confirm Password': 'تأكيد كلمة المرور',
      'Add Guardian': 'إضافة وليّ الأمر',

      'Email': 'البريد الإلكتروني',
      'Guardian Username': 'اسم المستخدم لوَليّ الأمر',
      'Name': 'الاسم',
      'phone Number': 'رقم الهاتف ',
      'National ID': 'الرقم الوطني',

      'Set All As a Holiday': 'وضع عطلة للكل',
      'Cause': 'السبب',
      'Enter The Reason For Absence': 'أدخل سبب الغياب',
      'The reason for the absence of the all students': 'سبب غياب جميع الطلاب',
      'Present': 'حاضر',
      'Truant': 'غائب',
      'Late': 'متأخر',
      'Holiday': 'عطلة',
      'The reason for the absence of the student': 'سبب غياب الطالب',
      'Attendance Today Has Been Uploaded': 'الحضور رفع اليوم',
      'Attendence': '',
      "att": "حضور",
      'Subject': 'المادة',
      'Add Teacher': 'إضافة معلم',
      'Contract Type': 'نوع العقد',
      'Full Time': 'دوام كامل',
      'hours': 'ساعات',
      'Hours': 'ساعات',
      'This Teacher Does Not Contain Any Data': 'هذا المعلم ليس لديه أي بيانات',
      'Mobile: ': 'الهاتف: ',
      'Teacherr': '',
      'Do You Want To Deletet': 'هل تريد حذف المعلم',
      'Delete Teacher': 'حذف المعلم',
      'If You Deselected The Illness The File Will Remove':
          'إذا أردت إلغاء تحديد المرض , سوف يحذف الملف',
      'If You Click Yes The File Will Remove': 'إذا ضغطت نعم , الملف سوف يحذف',
      'illness File': 'ملف مرض',
      'Vaccine File': 'ملف لقاح',
      'Employee Illness': 'أمراض الموظف',
      'Teacher Illness': 'أمراض المعلم',
      'The reason for the absence of the all Teachers': 'سبب غياب كل المعلمين',
      'Vacation': 'إجازة',
      "sub": "مواد",
      "No Guardian": "لا يوجد أولياء أمور",

      'Subjects': '',
      'Rewards Students': 'مكافئة الطالب',
      'Rewards & Penalties': 'مكافئات و عقوبات',
      'My Account': 'حسابي',
    },
    'en': {
      'Welcome Laith Haitham Azzam': 'Welcome Laith Haitham Azzam',
      'Have A Nice Day At Work': 'Have A Nice Day At Work',
      'Illness and Vaccines': 'Illness and Vaccines',
      'Illness': 'Illness',
      'No Guardian': 'No Guardian',
      'Rewards Students': 'Rewards Students',
      'Rewards & Penalties': 'Rewards & Penalties',
      'Vaccines': 'Vaccines',
      'Rewards and Penalties': 'Rewards and Penalties',
      'Rewards': 'Rewards',
      'Penalties': 'Penalties',
      'Attendance Today': 'Attendance Today',
      'Employees\nAttendance': 'Employees\nAttendance',
      'Students\nAttendance': 'Students\nAttendance',
      'Teachers\nAttendance': 'Teachers\nAttendance',
      'Percentage\nStudents': 'Percentage\nStudents',
      'Percentage\nTeacher': 'Percentage\nTeacher',
      'Percentage\nEmployee': 'Percentage\nEmployee',
      'Total Students': 'Total Students',
      'Total Teacher': 'Total Teacher',
      'Total Employee': 'Total Employee',
      'Total Visitor': 'Total Visitor',
      'Total Books': 'Total Books',
      'Total Division': 'Total Division',
      'Dashboard': 'Dashboard',
      'Complete the registration details before starting':
          'Complete the registration details before starting',
      'Enroll Requests': 'Enroll Requests',
      'Exam Table': "Exam Table",
      'School Time Table': 'School Time Table',
      'All Students': 'All Students',
      'Study Year Students': 'Study Year Students',
      'All Guardians': 'All Guardians',
      'Student Attendance': 'Student Attendance',
      'Students Attendance Managment': 'Students Attendance Managment',
      'Teacher Management': 'Teacher Management',
      'Teacher Status': 'Teacher Status',
      'Teacher Attendance Managment': 'Teacher Attendance Managment',
      'Employee Management': 'Employee Management',
      'Employee Attendance': 'Employee Attendance',
      'Employee Attendance Manage': 'Employee Attendance Manage',
      'Virtual User Management': 'Virtual User Management',
      'Session Management': 'Session Management',
      'Grade Management': 'Grade Management',
      'Subject Management': 'Subject Management',
      'Class Management': 'Class Management',
      'Division Management': 'Division Management',
      'Curriculum Management': 'Curriculum Management',
      'School Data Management': 'School Data Management',
      'Electronic Library': 'Electronic Library',
      'Transaction': 'Transaction',
      'My Email': 'My Email',
      'Illness Screen': 'Illness Screen',
      'Vaccine Screen': 'Vaccine Screen',
      'Presence of students': 'Presence of students',
      'Presence this session students': 'Presence 2024 students',
      'Total this year': 'Total this year',
      'Add': 'Add',
      'Penalty En - Name': 'Penalty En - Name',
      'Penalty Ar - Name': 'Penalty Ar - Name',
      'Details': 'Details',
      'Add Penalty': 'Add Penalty',
      'Delete': 'Delete',
      'Cancel': 'Cancel',
      'Old Password': 'Old Password',
      'Do You Want To Delete': 'Do You Want To Delete',
      'penalty': 'penalty',
      'Edit': 'Edit',
      'No Attendance': 'No Attendance',
      'Operation': 'Operation',
      'Penalty Name': 'Penalty Name',
      'Delete Penalty': 'Delete Penalty',
      'Edit Penalty': 'Edit Penalty',
      'Status': 'Status',
      'No Requests': 'No Requests',
      'Guardian Info :': 'Guardian Info :',
      'Name :': 'Name :',
      'Mobile:': 'Mobile:',
      'Email: ': 'Email: ',
      'National ID:': 'National ID:',
      'Student Info:': 'Student Info:',
      'Current Class:': 'Current Class:',
      'Previous Class:': 'Previous Class',
      'Manage': 'Manage',
      'Reject': 'Reject',
      'Approve': 'Approve',
      'Rejected': 'Rejected',
      'Pending': 'Pending',
      'Partially': 'Partially',
      'Search By Name': 'Search By Name',
      'Class': 'Class',
      'Division': 'Division',
      'Manage Student': 'Manage Student',
      'Add Exam': 'Add Exam',
      'Date': 'Date',
      'Type': 'Type',
      'Quiz Type': 'Quiz Type',
      'No Rewards': 'No Rewards',
      'No Penalty': 'No Penalty',
      'Curriculum Name': 'Curriculum Name',
      'Period': 'Period',
      'Max Mark': 'Max Mark',
      'Passing Mark': 'Passing Mark',
      'Operations': 'Operations',
      'Edit Exam': 'Edit Exam',
      'Semester': 'Semester',
      'Curriculum': 'Curriculum',
      'season': 'semester',
      'New Text': 'New Text',
      'Min Mark': 'Min Mark',
      'Time': 'Time',
      'Morning': 'Morning',
      'Evening': 'Evening',

      'Search': 'Search',
      'Settings': 'Settings',
      'Profile': 'Profile',
      'Personal': 'Personal',
      'Password': 'Password',
      'Appearance': 'Appearance and Language',
      'Light Theme': 'Light Theme',
      'Dark Theme': 'Dark Theme',
      'Language': 'Language',
      'English': 'English',
      'Arabic': 'العربية',
      'Logout': 'Logout',
      'Logout from Current Session': 'Logout from Current Session',
      'Logout from All Sessions': 'Logout from All Sessions',
      'Edit Picture': 'Edit Picture',
      'Delete Picture': 'Delete Picture',
      'Application Theem': 'Application Theme',
      'Application and Profile Settings': 'Application and Profile Settings',
      '': '',
      'Personal Information': 'My General Details',
      'Social Media Info': 'Social Media Info',
      'Bank Info': 'Bank Info',
      'Account And Password': 'Account And Password',
      'Your Password': 'Your Password',
      'Your Verification Code': 'Your Verification Code',
      'Change Password': 'Change Password',
      'New Password': 'New Password',
      'Confirm New Password': 'Confirm New Password',
      'More Information': 'More Information',
      'First Name': 'First Name',
      'Last Name': 'Last Name',
      'Phone Number': 'Phone Number',
      'Emergency Number': 'Emergency Number',
      'Join Date': 'Join Date',
      'Birthdate': 'Birthdate',
      'Address': 'Address',
      'Current Address': 'Current Address',
      'Gender': 'Gender',
      'Family Status': 'Family Status',
      'Career History': 'Career History',
      'Qualification': 'Qualification',
      'Experience': 'Experience',
      'Note': 'Note',
      'Save': 'Save',
      'Next': 'Next',
      'Facebook URL': 'Facebook URL',
      'Instagram URL': 'Instagram URL',
      'X Platform URL': 'X Platform URL',
      'Linkedin URL': 'Linkedin URL',
      'Bank Name': 'Bank Name',
      'Bank Account Title': 'Bank Account Title',
      'Bank Branch Name': 'Bank Branch Name',
      'Bank Account Number': 'Bank Account Number',
      'Select Class First': 'Select Class First',
      'Select Division First': 'Select Division First',
      'Day': 'Day',
      'Add Your Photo Profile': 'Add Your Photo Profile',
      'Teacher': 'Teacher',
      'Operation of Lessons': 'Operation of Lessons',
      'Sunday': 'Sunday',
      'Monday': 'Monday',
      'Tuesday': 'Tuesday',
      'Wednesday': 'Wednesday',
      'Thursday': 'Thursday',
      'First\n Lesson': 'First\n Lesson',
      'second\n Lesson': 'second\n Lesson',
      'Third\n Lesson': 'Third\n Lesson',
      'Forth\n Lesson': 'Forth\n Lesson',
      'Fifth\n Lesson': 'Fifth\n Lesson',
      'Sixth\n Lesson': 'Sixth\n Lesson',
      'Seventh\n Lesson': 'Seventh\n Lesson',
      'Session': 'Session',
      'Grade': 'Grade',
      'Email:': 'Email:',
      'Grade Level:': 'Grade Level:',
      'Delete Students': 'Delete Student',
      'Student': 'Student',
      'No Students': 'No Students',
      'Reward': 'Reward',
      'Penalty': 'Penalty',
      'Start Date': 'Start Date',
      'End Date': 'End Date',
      'Reason': 'Reason',
      'Penalties And Rewards': 'Penalties And Rewards',
      'Passing': 'Passing',
      'Failed': 'Failed',
      'Export Certificate': 'Export Certificate',
      'Send': 'Send',
      'Penaltyy': 'Penalty',
      'The Reason': 'The Reason',
      'Punishing Student': 'Punishing Student',
      'Punishing': 'Punishing',
      'Contact Us': 'Contact Us',
      'AboutUs': 'AboutUs',
      'WhyUs': 'WhyUs',
      'Programs': 'Programs',
      'Enrollment': 'Enrollment',
      'Eligibility': 'Eligibility',
      'Who Can We Register At Virtual Modern School':
          'Who Can We Register At Virtual Modern School',
      'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary':
          'Anyone who resides outside Syria desires to learn the Syrian Educational Curriculums from Elementary',
      'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted':
          'to Middle and High schools can enroll and graduate to be awarded the High school Diploma granted',
      'by the Ministry of Education at Syrian Arab Republic':
          'by the Ministry of Education at Syrian Arab Republic',
      'Back': 'Back',
      'Add Students': 'Add Students',
      'Mobile Number :': 'Mobile Number :',
      'Select Garduans To Add Students': 'Select Garduans To Add Students',
      'Place Of Birth': 'Place Of Birth',
      'Religion': 'Religion',
      'Blood Type': 'Blood Type',
      'Location': 'Location',
      'Mobile Number': 'Mobile Number',
      'FamilyState': 'FamilyState',
      'National Id': 'National Id',
      'Special need': 'Special need',
      'Martyr son': 'Martyr son',
      'Student Illness': 'Student Illness',
      'Student Vaccines': 'Student Vaccines',
      '   Student School Info   ': '   Student School Info   ',
      'Username': 'Username',
      'Fee Discount': 'Fee Discount',
      '   Father Info   ': '   Father Info   ',
      'Father Name': 'Father Name',
      'Father Phone': 'Father Phone',
      'Father Work': 'Father Work',
      '   Mother Info   ': '   Mother Info   ',
      'Mother Name': 'Mother Name',
      'Mother Phone': 'Mother Phone',
      'Mother Work': 'Mother Work',
      '   More Info   ': '   More Info   ',
      'Last School Details': 'Last School Details',
      '   File Data   ': '   File Data   ',
      'Add Father Passport': 'Add Father Passport',
      'File Father Passport Dropped!': 'File Father Passport Dropped!',
      'Add Mother Passport': 'Add Mother Passport',
      'File Mother Passport Dropped!': 'File Mother Passport Dropped!',
      'Add Son Passport': 'Add Son Passport',
      'File Son Passport Dropped!': 'File Son Passport Dropped!',
      'Add ID File': 'Add ID File',
      'File Id Dropped!': 'File Id Dropped!',
      'Add Certificate': 'Add Certificate',
      'File Certificate Dropped!': 'File Certificate Dropped!',
      'Add Academic sequence': 'Add Academic sequence',
      'File Academic sequence Dropped!': 'File Academic sequence Dropped!',
      'Add Family notebook': 'Add Family notebook',
      'File Family notebook Dropped!': 'File Family notebook Dropped!',
      'Local ID': 'Local ID',
      'Male': 'Male',
      'Female': 'Female',
      'Muslim': 'Muslim',
      'Christian': 'Christian',
      'Widow': 'Widow',
      'Single': 'Single',
      'Married': 'Married',
      'Divorced': 'Divorced',
      'Click To Add Father Passport\nOr\nDrag And Drop File Here':
          'Click To Add Father Passport\nOr\nDrag And Drop File Here',
      'Done Selected File': 'Done Selected File',
      'Click To Add Mother Passport\nOr\nDrag And Drop File Here':
          'Click To Add Mother Passport\nOr\nDrag And Drop File Here',
      'Click To Add Son Passport\nOr\nDrag And Drop File Here':
          'Click To Add Son Passport\nOr\nDrag And Drop File Here',
      'Click To Add Id\nOr\nDrag And Drop File Here':
          'Click To Add Id\nOr\nDrag And Drop File Here',
      'Click To Add Certificate\nOr\nDrag And Drop File Here':
          'Click To Add Certificate\nOr\nDrag And Drop File Here',
      'Click To Add Academic sequence\nOr\nDrag And Drop File Here':
          'Click To Add Academic sequence\nOr\nDrag And Drop File Here',
      'Click To Add Family notebook\nOr\nDrag And Drop File Here':
          'Click To Add Family notebook\nOr\nDrag And Drop File Here',
      'Syria': 'Syria',
      'Done': 'Done',
      'Student illeness': 'Student illeness',
      'Student Vaccine': 'Student Vaccine',
      'Add Picture': 'Add Picture',

////////////////////////////////section 1 and home appbar////////////////////////////////////
      'WE CARE ABOUT \n YOUR FUTURE': 'WE CARE ABOUT \n YOUR FUTURE',
      'Join us to enter a better world filled with advanced educational methods through Virtual Modern School':
          'Join us to enter a better world filled with advanced educational methods through Virtual Modern School',
      'Enroll': 'Enroll',
      'Sign In': 'Sign In',
      'Teachers': 'Teachers',
      'Students': 'Students',
      'Visitors': 'Visitors',
/////////////////////////section 2////////////////////////////////////////////
      'People with special needs who are residing in Syria are uncapable to study in regular schools uncapable':
          'People with special needs who are residing in Syria are uncapable to study in regular schools uncapable',
      'to study uncapable to study in regular schools and exceptional students cases determined by the':
          'to study uncapable to study in regular schools and exceptional students cases determined by the',
      'Ministry of Education at Syrian Arab Diploma granted by the Ministry of Education at Syrian Arab':
          'Ministry of Education at Syrian Arab Diploma granted by the Ministry of Education at Syrian Arab',
      'Republic': 'Republic',
      //////////////////////////////section 3/////////////////////////////
      'How I Can Enroll At Virtual Modern School':
          'How I Can Enroll At Virtual Modern School',
      'Parents of our students can register their children in the Virtual Modern School':
          'Parents of our students can register their sons in the Virtual Modern School',
      'by the following steps:': 'by the following steps:',
      '1. Enter the first and last name of the guardian':
          '1. Enter the first and last name of the guardian',
      '2. Enter the mobile phone number of guardian':
          '2. Enter the mobile phone number of guardian',
      '3. Enter the Syrian national number of the guardian':
          '3. Enter the Syrian national number of the guardian',
      'Read More': 'Read More',
      //////////////////////////////////section 4/////////////////////////////////////
      'Why Us?': 'Why Us?',
      'Virtual Modern School is an online learning platform that helps students to learn the':
          'Virtual Modern School is an online learning platform that helps students to learn the',
      'Syrian Education Curriculum from home. The courses of this platform are designed':
          'Syrian Education Curriculum from home. The courses of this platform are designed',
      'for elementary school, middle school, and high school all in one place.':
          '.for elementary school, middle school, and high school all in one place',
      'Improving educational': 'Improving educational',
      'Skills': 'Skills',
      'Smart virtual': 'Smart virtual',
      'meeting': 'meeting',
      'Outstanding': 'Outstanding',
      'user - friendliness': 'user - friendliness',
      'Instant live': 'Instant live',
      'Lessons': 'Lessons',
      'Focus on results': 'Focus on results',
      'Multiple registration': 'Multiple registration',
      'options': 'options',
      ////////////////////////////// section 5/////////////////////////////////////
      'Who Are We': 'Who Are We',
      'is a community of learners, including students, parents, and staff, dedicated to creating a rigorous and':
          'is a community of learners, including students, parents, and staff, dedicated to creating a rigorous and',
      'VIRTUAL MODERN SCHOOL (VMS)': 'VIRTUAL MODERN SCHOOL (VMS)',
      'inclusive educational environment. VMS students are goal-oriented, critical thinkers, and community leaders':
          'inclusive educational environment. VMS students are goal-oriented, critical thinkers, and community leaders',
      'committed to achieving high levels of integrity and academic success.':
          '.committed to achieving high levels of integrity and academic success',
      'VIRTUAL MODERN SCHOOL (VMS) staff aim to create a supportive':
          'VIRTUAL MODERN SCHOOL (VMS) staff aim to create a supportive',
      'and challenging environment for all students to reach their potential,':
          'and challenging environment for all students to reach their potential,',
      'engaging in continuous improvement through goal setting and':
          'engaging in continuous improvement through goal setting and',
      'reflection': '.reflection',
      'Virtual Modern School': 'Virtual Modern School',

      /////////////////////section 6///////////////////////////

      'What Do We': 'What Do We',
      'We develop a culture of excellence that includes a robust instructional program aligned to the':
          'We develop a culture of excellence that includes a robust instructional program aligned to the',
      'highest standards with a focus on implementing balanced literacy through reading and writing':
          'highest standards with a focus on implementing balanced literacy through reading and writing',
      'workshops, while cultivating competency across all subject areas.':
          '.workshops, while cultivating competency across all subject areas',
      'We are committed to developing well-rounded students who embody our core values: Be Safe, Be Respectful, Be Responsible, and Be Mindful. Our vibrant learning environment encourages discovery and creative expression, making every student feel valued.\n\nWe provide our educators with robust professional development to enhance teaching practices and boost student success. Through collaboration and a community schools model, we align resources to ensure every student thrives. Join us in our journey towards excellence!':
          'We are committed to developing well-rounded students who embody our core values: Be Safe, Be Respectful, Be Responsible, and Be Mindful. Our vibrant learning environment encourages discovery and creative expression, making every student feel valued \n\nWe provide our educators with robust professional development to enhance teaching practices and boost student success. Through collaboration and a community schools model, we align resources to ensure every student thrives. Join us in our journey towards excellence',

      //////////////////////////section 7////////////////////////////
      'Openning Hours': 'Openning Hours',
      '8 AM -----> 1 PM': 'from 8 AM at 1 PM',
      '3 PM -----> 8 PM': 'from 3 PM at 8 PM',
      'Contact Details': 'Contact Details',
      'Shakib Arslan Street - Engineers Syndicate Building - 2nd Floor - AlSuwaidaa - Syria':
          'Shakib Arslan Street - Engineers Syndicate Building - 2nd Floor - AlSuwaidaa - Syria',
      'All Rights reserved. Copyright': 'All Rights reserved. Copyright',
      //////////////////////////////////////////////
      'Login': 'Login',
      'Update Student': 'Update Student',
      'Pend Student': 'Pend Student',
      'Do You Want To Pend ': 'Do You Want To Pend ',
      'Student?': 'Student?',
      'Yes': 'Yes',
      'No': 'No',
      'UnPend Student': 'UnPend Student',
      'Do You Want To UnPend': 'Do You Want To UnPend',
      'UnPend This Student': 'UnPend This Student',
      'Realagon': 'Religion',
      'Family State': 'Family State',
      'Last School Detail': 'Last School Detail',
      'Edit Student': 'Edit Student',
      'Edite': 'Edit',
      'Info': 'Info',

      'Show only selected items': 'Show only selected items',
      'Do You Want To Deletee': 'Do You Want To Delete',
      'No Result': 'No Result',

      'Guardian Name': 'Guardian Name',
      'Guardian National ID': 'Guardian National ID',
      'Guardian Email': 'Guardian Email',
      'Guardian Phone Number': 'Guardian Phone Number',
      'Edit Guardian': 'Edit Guardian',
      'Confirm Password': 'Confirm Password',

      'Add Guardian': 'Add Guardian',
      'Email': 'Email',
      'Guardian Username': 'Guardian Username',
      'Name': 'Name',
      'phone Number': 'phone Number',
      'National ID': 'National ID',

      'Set All As a Holiday': 'Set All As a Holiday',
      'Cause': 'Cause',
      'Enter The Reason For Absence': 'Enter The Reason For Absence',
      'The reason for the absence of the all students':
          'The reason for the absence of the all student',
      'Present': 'Present',
      'Truant': 'Truant',
      'Late': 'Late',
      'Holiday': 'Holiday',
      'The reason for the absence of the student':
          'The reason for the absence of the student',
      'Attendance Today Has Been Uploaded':
          'Attendance Today Has Been Uploaded',

      'Attendence': 'Attendence',
      'Subject': 'Subject',
      'Add Teacher': 'Add Teacher',
      'Contract Type': 'Contract Type',

      'Full Time': 'Full Time',
      'hours': 'hours',
      'Hours': 'Hours',

      'This Teacher Does Not Contain Any Data':
          'This Teacher Does Not Contain Any Data',
      'Mobile: ': 'Mobile: ',

      'Teacherr': 'Teacherr',
      'Do You Want To Deletet': 'Do You Want To Delete',
      'Delete Teacher': 'Delete Teacher',

      'If You Deselected The Illness The File Will Remove':
          'If You Deselected The Illness The File Will Remove',
      'If You Click Yes The File Will Remove':
          'If You Click Yes The File Will Remove',
      'illness File': 'illness File',
      'Vaccine File': 'Vaccine File',
      'Employee Illness': 'Employee Illness',
      'Teacher Illness': 'Teacher Illness',

      'The reason for the absence of the all Teachers':
          'The reason for the absence of the all Teachers',
      'Vacation': 'Vacation',
      "att": "",
      "sub": "",

      'Subjects': 'Subjects',
      'My Account': 'My Account',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
      '': '',
    }
  };
}
