import 'package:get/get.dart';
import 'package:vms_school/Link/Controller/AdminController/DrowerController.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/Add_Data_controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/Add_Full_Employee_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/AllEmpolyeeController.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/All_Virtual_Employee_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/DataController.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/EmployeeAttendenceController.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/Employeeecontroller.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/Virtual_Employee_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Employee_Controllers/oneEmployeeAttendenceController.dart';
import 'package:vms_school/Link/Controller/AdminController/Location_controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Main_Admin_Controller/AdminHomeContentController.dart';
import 'package:vms_school/Link/Controller/AdminController/Main_Admin_Controller/Admin_DropDown_Profile_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Main_Admin_Controller/Admin_Profile_Content.dart';
import 'package:vms_school/Link/Controller/AdminController/Main_Admin_Controller/Dashboard_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Admin_School_Time.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Class_Mgmt_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Divisions_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/ExamTableController.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/ExamTableDialogController.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Grade_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Illness_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Labrary_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/PenaltyController.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Rewards_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/School_Content_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/School_Info_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Session_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Subject_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Teachernote_and_GradeReco.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Transaction_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/Vaccines_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/School_Controllers/ValidateTeacherNoteAndGradeReco.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/Add_Students_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/AdminStudentsAttendens.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/AllStudentsController.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/PenaltiesAndRewardsController.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/RequestsController.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/Student_Attendenc_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/Students_Marks_Controller.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/StudyYearStudentsController.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/allGaurdianController.dart';
import 'package:vms_school/Link/Controller/AdminController/Teacher_Controllers/AddTeacherController.dart';
import 'package:vms_school/Link/Controller/AdminController/Teacher_Controllers/AllTeacherAtendenceController.dart';
import 'package:vms_school/Link/Controller/AdminController/Teacher_Controllers/AllTeachersController.dart';
import 'package:vms_school/Link/Controller/AdminController/Teacher_Controllers/TeacherSubjectsController.dart';
import 'package:vms_school/Link/Controller/AdminController/Students_Controllers/oneStudentAttendenceController.dart';
import 'package:vms_school/Link/Controller/AuthController/Enroll_Controller.dart';
import 'package:vms_school/Link/Controller/AuthController/UserController.dart';
import 'package:vms_school/Link/Controller/GuardianController/AddGurdianChildController.dart';
import 'package:vms_school/Link/Controller/GuardianController/ChildExamTableController.dart';
import 'package:vms_school/Link/Controller/GuardianController/Guardian_My_Data_Controller.dart';
import 'package:vms_school/Link/Controller/GuardianController/MyChildren_Controller.dart';
import 'package:vms_school/Link/Controller/GuardianController/Students_Marks_Gua_Controller.dart';
import 'package:vms_school/Link/Controller/HomeController/HomeScreenController.dart';
import 'package:vms_school/Link/Controller/LMS_Controllers/Admin_LMS/Selected_Screen.dart';
import 'package:vms_school/Link/Controller/Teacher_Controller/My_Students_Controller.dart';
import 'package:vms_school/Link/Controller/Teacher_Controller/QuizTableTeacherController.dart';
import 'package:vms_school/Link/Controller/Teacher_Controller/StudentMarks_TeacherController.dart';
import 'package:vms_school/Link/Controller/Teacher_Controller/StudyShareTeacherController.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownClassesController.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownCuriculmController.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownCurriculumn_Controller.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownDivisionController.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownExamTypeController.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownGradeController.dart.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownPenaltyController.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/DropDownSemsterController.dart';
import 'package:vms_school/Link/Controller/WidgetController/DropDown_Controllers/Sessions_DropDown_Controller.dart';
import 'package:vms_school/Link/Controller/WidgetController/OtherWidget/DateControler.dart';
import 'package:vms_school/Link/Controller/WidgetController/OtherWidget/DropDownController.dart';
import 'package:vms_school/Link/Controller/WidgetController/OtherWidget/PasswordHintController.dart';
import 'package:vms_school/Theme/themeController.dart';
import 'package:vms_school/Translate/local_controller.dart';
import 'package:vms_school/view/Both_Platform/widgets/SidbarAnimation.dart';

class AppBindings extends Bindings {
  @override
  void dependencies() {
    Get.lazyPut(() => ThemeController(), fenix: true);
    Get.lazyPut(() => UserController(), fenix: true);
    Get.lazyPut(() => PasswordHintController(), fenix: true);
    Get.lazyPut(() => ThemeController(), fenix: true);
    Get.lazyPut(() => AdminHomeContentController(), fenix: true);
    Get.lazyPut(() => Homescreencontroller(), fenix: true);
    Get.lazyPut(() => ExamTableController(), fenix: true);
    Get.lazyPut(() => Requestscontroller(), fenix: true);
    Get.lazyPut(() => DropDownController(), fenix: true);
    Get.lazyPut(() => Allgaurdiancontroller(), fenix: true);
    Get.put(Allteachercontroller(), permanent: true);
    Get.lazyPut(() => Allstudentscontroller(), fenix: true);
    Get.lazyPut(() => Student_attendence_controller(), fenix: true);
    Get.lazyPut(() => EmployeeController(), fenix: true);
    Get.lazyPut(() => AdminSchoolTimeController(), fenix: true);
    Get.lazyPut(() => StudyYearStudentsController(), fenix: true);
    Get.lazyPut(() => StudentAttendencController(), fenix: true);
    Get.lazyPut(() => SessionController(), fenix: true);
    Get.lazyPut(() => Grade_Controller(), fenix: true);
    Get.lazyPut(() => ClassMgmtController(), fenix: true);
    Get.lazyPut(() => Divisions_Controller(), fenix: true);
    Get.lazyPut(() => Curriculumn_Controller(), fenix: true);
    Get.lazyPut(() => SchoolInfoController(), fenix: true);
    Get.lazyPut(() => Dropdowngradecontroller(), fenix: true);
    Get.lazyPut(() => Dropdownclassescontroller(), fenix: true);
    Get.lazyPut(() => Allempolyeecontroller(), fenix: true);
    Get.lazyPut(() => Labrary_Controller(), fenix: true);
    Get.lazyPut(() => Dropdowndivisioncontroller(), fenix: true);
    Get.lazyPut(() => DatePickerController(), fenix: true);
    Get.lazyPut(() => Dashboard_Controller(), fenix: true);
    Get.lazyPut(() => AddFullEmployeeController(), fenix: true);
    Get.lazyPut(() => All_Screen_Sessions_Controller(), fenix: true);
    Get.lazyPut(() => Dropdownexamtypecontroller(), fenix: true);
    Get.lazyPut(() => Onestudentattendencecontroller(), fenix: true);
    Get.lazyPut(() => Dropdownpenaltycontroller(), fenix: true);
    Get.lazyPut(() => Dropdownsemstercontroller(), fenix: true);
    Get.lazyPut(() => Virtual_Employee_Controller(), fenix: true);
    Get.lazyPut(() => All_Virtual_Employee_Controller(), fenix: true);
    Get.lazyPut(() => Employeeattendencecontroller(), fenix: true);
    Get.lazyPut(() => Oneemployeeattendencecontroller(), fenix: true);
    Get.lazyPut(() => Subject_Controller(), fenix: true);
    Get.lazyPut(() => Allteacheratendencecontroller(), fenix: true);
    Get.lazyPut(() => Dropdowncuriculmcontroller(), fenix: true);
    Get.lazyPut(() => Transaction_Controller(), fenix: true);
    Get.lazyPut(() => Add_Students_Controller(), fenix: true);
    Get.lazyPut(() => Location_controller(), fenix: true);
    Get.lazyPut(() => Illness_Controller(), fenix: true);
    Get.lazyPut(() => Vaccines_Controller(), fenix: true);
    Get.lazyPut(() => Addteachercontroller(), fenix: true);
    Get.lazyPut(() => Penaltycontroller(), fenix: true);
    Get.lazyPut(() => Penaltiesandrewardscontroller(), fenix: true);
    Get.lazyPut(() => Teachersubjectscontroller(), fenix: true);
    Get.lazyPut(() => TeachernoteAndGradeReco(), fenix: true);
    Get.lazyPut(() => Admin_Profile_Content(), fenix: true);
    Get.lazyPut(() => LocalizationController(), fenix: true);
    Get.lazyPut(() => Profile_DropDown_Controller(), fenix: true);
    Get.lazyPut(() => RewardsController(20.0, true));
    Get.put(Add_Data_controller(), permanent: true);
    Get.lazyPut(() => Students_Marks_Controller(), fenix: true);
    Get.lazyPut(() => errorHandel(), fenix: true);
    Get.lazyPut(() => SidebarController(), fenix: true);
    Get.lazyPut(() => School_Content_Controller(), fenix: true);
    Get.lazyPut(() => DraweController(), fenix: true);
    Get.lazyPut(() => EnrollController(), fenix: true);
    Get.lazyPut(() => Validateteachernoteandgradereco(), fenix: true);
    Get.lazyPut(() => MyChildren_Controller(), fenix: true);
    Get.lazyPut(() => Childexamtablecontroller(), fenix: true);
    Get.lazyPut(() => Guardian_My_Data_Controller(), fenix: true);
    Get.lazyPut(() => Addgurdianchildcontroller(), fenix: true);
    Get.lazyPut(() => My_Students_Controller(), fenix: true);
    Get.lazyPut(() => Studyshareteachercontroller(), fenix: true);
    Get.lazyPut(() => Quiztableteachercontroller(), fenix: true);
    Get.lazyPut(() => Students_Marks_Gua_Controller(), fenix: true);
    Get.lazyPut(() => StudentmarksTeachercontroller(), fenix: true);
    Get.lazyPut(() => Examtabledialogcontroller(), fenix: true);
    //...................................LMS Bindings.......................................................//
    Get.lazyPut(() => Selected_Class_Controller(), fenix: true);
  }
}
