// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'vms_school';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String CAIRO_BOLD = 'Cairo-Bold';
  static const String CAIRO_REGULAR = 'Cairo-Regular';
  static const String FICONS = 'Ficons';
  static const String SANSATION_REGULAR = 'Sansation_Regular';
  static const String VMS_ICONS = 'VMS_Icons';
}
