/// Flutter icons LMS_Icons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LMS_Icons
///      fonts:
///       - asset: fonts/LMS_Icons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LMS_Icons {
  LMS_Icons._();

  static const _kFontFam = 'LMS_Icons';
  static const String? _kFontPkg = null;

  static const IconData fill = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tf = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData same = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData multiselect = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragdrop = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData paper = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checkone = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData curr_lms = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData links_lms = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData files_lms = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData divisions_lms = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pages_lms = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quiz_lms = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData qustion_bank_lms = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sopor_lms = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
